//convex/schema.js
import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

const seoulForecastStatus = v.union(
  v.literal("ok"),
  v.literal("partial"),
  v.literal("error"),
);

const seoulProviderStatus = v.union(v.literal("ok"), v.literal("error"));

const seoulHourlyForecastRow = v.object({
  date: v.string(),
  forecastTimeUtc: v.number(),
  forecastTimeLocal: v.string(),
  tempC: v.number(),
  tempF: v.number(),
  phrase: v.optional(v.string()),
  cloudCoverPct: v.optional(v.number()),
});

const seoulProviderDetail = v.object({
  provider: v.union(
    v.literal("weathercom"),
    v.literal("google"),
    v.literal("open_meteo"),
  ),
  label: v.string(),
  status: seoulProviderStatus,
  error: v.optional(v.string()),
  weight: v.number(),
  rawHighC: v.optional(v.number()),
  rawHighF: v.optional(v.number()),
  adjustedHighC: v.optional(v.number()),
  adjustedHighF: v.optional(v.number()),
  dailyHighC: v.optional(v.number()),
  dailyHighF: v.optional(v.number()),
  dailyPeakTimeUtc: v.optional(v.number()),
  dailyPeakTimeLocal: v.optional(v.string()),
  liveBiasC: v.optional(v.number()),
  capturedAt: v.optional(v.number()),
  capturedAtLocal: v.optional(v.string()),
  captureAgeMinutes: v.optional(v.number()),
  peakTimeUtc: v.optional(v.number()),
  peakTimeLocal: v.optional(v.string()),
  peakSourceCapturedAt: v.optional(v.number()),
  peakSourceCapturedAtLocal: v.optional(v.string()),
  pointCount: v.number(),
});

const seoulPredictionStatus = v.union(
  v.literal("awaiting_observations"),
  v.literal("on_track"),
  v.literal("running_warm"),
  v.literal("running_cool"),
  v.literal("limited_guidance"),
  v.literal("revised_up"),
  v.literal("revised_down"),
  v.literal("peak_likely_passed"),
  v.literal("final"),
);

export default defineSchema({
  notes: defineTable({
    stationIcao: v.optional(v.string()),
    title: v.optional(v.string()),
    body: v.optional(v.string()),
    imageIds: v.array(v.id("_storage")),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_createdAt", ["createdAt"]),

  monthRuns: defineTable({
    stationIcao: v.string(),
    stationIem: v.string(),
    year: v.number(),
    month: v.number(),
    manualUnit: v.union(v.literal("C"), v.literal("F")),
    createdAt: v.number(),
    updatedAt: v.number(),
    metarLastComputedAt: v.optional(v.number()),
    metarLastStatus: v.union(
      v.literal("idle"),
      v.literal("computing"),
      v.literal("ok"),
      v.literal("error"),
    ),
    metarLastError: v.optional(v.string()),
    metarAllLastComputedAt: v.optional(v.number()),
    metarAllLastStatus: v.optional(
      v.union(
        v.literal("idle"),
        v.literal("computing"),
        v.literal("ok"),
        v.literal("error"),
      ),
    ),
    metarAllLastError: v.optional(v.string()),
  }).index("by_station_month", ["stationIcao", "year", "month"]),

  dailyComparisons: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    manualMaxC: v.optional(v.number()),
    manualMaxF: v.optional(v.number()),
    manualNotes: v.optional(v.string()),
    metarMaxC: v.optional(v.number()),
    metarMaxF: v.optional(v.number()),
    metarMaxAtUtc: v.optional(v.number()),
    metarMaxAtLocal: v.optional(v.string()),
    metarObsCount: v.optional(v.number()),
    metarMaxRaw: v.optional(v.string()),
    metarMaxSource: v.optional(v.string()),
    deltaC: v.optional(v.number()),
    deltaF: v.optional(v.number()),
    metarAllMaxC: v.optional(v.number()),
    metarAllMaxF: v.optional(v.number()),
    metarAllMaxAtUtc: v.optional(v.number()),
    metarAllMaxAtLocal: v.optional(v.string()),
    metarAllObsCount: v.optional(v.number()),
    metarAllMaxRaw: v.optional(v.string()),
    metarAllMaxSource: v.optional(v.string()),
    deltaAllC: v.optional(v.number()),
    deltaAllF: v.optional(v.number()),
    updatedAt: v.number(),
  }).index("by_station_date", ["stationIcao", "date"]),

  kordPhoneCalls: defineTable({
    stationIcao: v.string(),
    date: v.string(), // YYYY-MM-DD (Chicago)
    slotLocal: v.string(), // YYYY-MM-DD HH:MM (Chicago) scheduled slot or manual trigger time
    tsUtc: v.optional(v.number()), // recording start (ms epoch)
    tsLocal: v.optional(v.string()), // YYYY-MM-DD HH:MM (Chicago), derived from tsUtc
    callSid: v.optional(v.string()),
    recordingSid: v.optional(v.string()),
    recordingUrl: v.optional(v.string()),
    recordingDuration: v.optional(v.number()),
    transcript: v.optional(v.string()),
    tempC: v.optional(v.number()),
    tempF: v.optional(v.number()),
    status: v.union(
      v.literal("queued"),
      v.literal("calling"),
      v.literal("recorded"),
      v.literal("transcribed"),
      v.literal("parsed"),
      v.literal("error"),
    ),
    error: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_station_date", ["stationIcao", "date"])
    .index("by_station_slot", ["stationIcao", "slotLocal"])
    .index("by_callSid", ["callSid"]),

  kordForecastSnapshots: defineTable({
    stationIcao: v.string(),
    stationName: v.string(),
    capturedAt: v.number(),
    capturedAtLocal: v.string(),
    durationDays: v.number(),
    unit: v.union(v.literal("imperial"), v.literal("metric")),
    language: v.string(),
    status: v.union(v.literal("ok"), v.literal("partial"), v.literal("error")),
    microsoftStatus: v.union(v.literal("ok"), v.literal("error")),
    microsoftError: v.optional(v.string()),
    microsoftForecastDays: v.array(
      v.object({
        date: v.string(),
        minTempC: v.optional(v.number()),
        minTempF: v.optional(v.number()),
        maxTempC: v.optional(v.number()),
        maxTempF: v.optional(v.number()),
        dayPhrase: v.optional(v.string()),
        nightPhrase: v.optional(v.string()),
      }),
    ),
    accuweatherStatus: v.optional(v.union(v.literal("ok"), v.literal("error"))),
    accuweatherError: v.optional(v.string()),
    accuweatherLocationKey: v.optional(v.string()),
    accuweatherForecastDays: v.optional(
      v.array(
        v.object({
          date: v.string(),
          minTempC: v.optional(v.number()),
          minTempF: v.optional(v.number()),
          maxTempC: v.optional(v.number()),
          maxTempF: v.optional(v.number()),
          dayPhrase: v.optional(v.string()),
          nightPhrase: v.optional(v.string()),
        }),
      ),
    ),
    googleStatus: v.optional(v.union(v.literal("ok"), v.literal("error"))),
    googleError: v.optional(v.string()),
    googleForecastDays: v.optional(
      v.array(
        v.object({
          date: v.string(),
          minTempC: v.optional(v.number()),
          minTempF: v.optional(v.number()),
          maxTempC: v.optional(v.number()),
          maxTempF: v.optional(v.number()),
          dayPhrase: v.optional(v.string()),
          nightPhrase: v.optional(v.string()),
        }),
      ),
    ),
    weathercomStatus: v.optional(v.union(v.literal("ok"), v.literal("error"))),
    weathercomError: v.optional(v.string()),
    weathercomForecastDays: v.optional(
      v.array(
        v.object({
          date: v.string(),
          minTempC: v.optional(v.number()),
          minTempF: v.optional(v.number()),
          maxTempC: v.optional(v.number()),
          maxTempF: v.optional(v.number()),
          dayPhrase: v.optional(v.string()),
          nightPhrase: v.optional(v.string()),
        }),
      ),
    ),
    actualReadings: v.array(
      v.object({
        source: v.string(),
        status: v.union(v.literal("ok"), v.literal("error")),
        observedAtUtc: v.optional(v.number()),
        observedAtLocal: v.optional(v.string()),
        tempC: v.optional(v.number()),
        tempF: v.optional(v.number()),
        raw: v.optional(v.string()),
        error: v.optional(v.string()),
      }),
    ),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_station_capturedAt", ["stationIcao", "capturedAt"]),

  kordCurrentSnapshots: defineTable({
    stationIcao: v.string(),
    stationName: v.string(),
    capturedAt: v.number(),
    capturedAtLocal: v.string(),
    unit: v.union(v.literal("imperial"), v.literal("metric")),
    language: v.string(),
    status: v.union(v.literal("ok"), v.literal("partial"), v.literal("error")),
    actualReadings: v.array(
      v.object({
        source: v.string(),
        status: v.union(v.literal("ok"), v.literal("error")),
        observedAtUtc: v.optional(v.number()),
        observedAtLocal: v.optional(v.string()),
        tempC: v.optional(v.number()),
        tempF: v.optional(v.number()),
        raw: v.optional(v.string()),
        error: v.optional(v.string()),
      }),
    ),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_station_capturedAt", ["stationIcao", "capturedAt"]),

  kordForecastPredictions: defineTable({
    stationIcao: v.string(),
    provider: v.union(
      v.literal("microsoft"),
      v.literal("accuweather"),
      v.literal("google"),
      v.literal("weathercom"),
    ),
    targetDate: v.string(),
    capturedAt: v.number(),
    capturedAtLocal: v.string(),
    captureDate: v.string(),
    leadDays: v.number(),
    minTempC: v.optional(v.number()),
    minTempF: v.optional(v.number()),
    maxTempC: v.optional(v.number()),
    maxTempF: v.optional(v.number()),
    dayPhrase: v.optional(v.string()),
    nightPhrase: v.optional(v.string()),
    snapshotId: v.id("kordForecastSnapshots"),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_station_provider_target_capturedAt", [
      "stationIcao",
      "provider",
      "targetDate",
      "capturedAt",
    ])
    .index("by_snapshotId", ["snapshotId"]),

  metarObservations: defineTable({
    stationIcao: v.string(),
    mode: v.union(v.literal("official"), v.literal("all")),
    date: v.string(),
    tsUtc: v.number(),
    tsLocal: v.string(),
    tempC: v.number(),
    tempF: v.number(),
    rawMetar: v.string(),
    source: v.string(),
    noaaFirstSeenAt: v.optional(v.number()),
    updatedAt: v.number(),
  }).index("by_station_mode_date_ts", ["stationIcao", "mode", "date", "tsUtc"]),

  synopticObservations: defineTable({
    stationIcao: v.string(),
    provider: v.string(),
    source: v.string(),
    date: v.string(),
    obsTimeUtc: v.number(),
    obsTimeLocal: v.string(),
    tempC: v.optional(v.number()),
    tempF: v.optional(v.number()),
    dewpointC: v.optional(v.number()),
    dewpointF: v.optional(v.number()),
    relativeHumidity: v.optional(v.number()),
    windDirDegrees: v.optional(v.number()),
    windSpeedMph: v.optional(v.number()),
    windSpeedMps: v.optional(v.number()),
    visibilityMiles: v.optional(v.number()),
    ceilingFt: v.optional(v.number()),
    altimeterInHg: v.optional(v.number()),
    seaLevelPressureMb: v.optional(v.number()),
    weatherCondition: v.optional(v.string()),
    weatherSummary: v.optional(v.string()),
    metarOrigin: v.optional(v.string()),
    rawMetar: v.optional(v.string()),
    firstSeenAt: v.number(),
    lastSeenAt: v.number(),
    updatedAt: v.number(),
  }).index("by_station_date_ts", ["stationIcao", "date", "obsTimeUtc"]),

  synopticDailySummaries: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    obsCount: v.number(),
    latestObsTimeUtc: v.optional(v.number()),
    latestObsTimeLocal: v.optional(v.string()),
    latestRawMetar: v.optional(v.string()),
    latestMetarOrigin: v.optional(v.string()),
    maxTempC: v.optional(v.number()),
    maxTempF: v.optional(v.number()),
    maxTempAtUtc: v.optional(v.number()),
    maxTempAtLocal: v.optional(v.string()),
    minTempC: v.optional(v.number()),
    minTempF: v.optional(v.number()),
    minTempAtUtc: v.optional(v.number()),
    minTempAtLocal: v.optional(v.string()),
    updatedAt: v.number(),
  }).index("by_station_date", ["stationIcao", "date"]),

  madisHfmObservations: defineTable({
    stationIcao: v.string(),
    provider: v.string(),
    source: v.string(),
    date: v.string(),
    obsTimeUtc: v.number(),
    obsTimeLocal: v.string(),
    tempC: v.optional(v.number()),
    tempF: v.optional(v.number()),
    dewpointC: v.optional(v.number()),
    dewpointF: v.optional(v.number()),
    relativeHumidity: v.optional(v.number()),
    windDirDegrees: v.optional(v.number()),
    windSpeedMps: v.optional(v.number()),
    windGustMps: v.optional(v.number()),
    altimeterPa: v.optional(v.number()),
    dewpointQcd: v.optional(v.string()),
    relativeHumidityQcd: v.optional(v.string()),
    tempQcd: v.optional(v.string()),
    windDirQcd: v.optional(v.string()),
    windSpeedQcd: v.optional(v.string()),
    windGustQcd: v.optional(v.string()),
    altimeterQcd: v.optional(v.string()),
    firstSeenAt: v.number(),
    lastSeenAt: v.number(),
    updatedAt: v.number(),
  }).index("by_station_date_ts", ["stationIcao", "date", "obsTimeUtc"]),

  madisHfmDailySummaries: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    obsCount: v.number(),
    latestObsTimeUtc: v.optional(v.number()),
    latestObsTimeLocal: v.optional(v.string()),
    maxTempC: v.optional(v.number()),
    maxTempF: v.optional(v.number()),
    maxTempAtUtc: v.optional(v.number()),
    maxTempAtLocal: v.optional(v.string()),
    minTempC: v.optional(v.number()),
    minTempF: v.optional(v.number()),
    minTempAtUtc: v.optional(v.number()),
    minTempAtLocal: v.optional(v.string()),
    updatedAt: v.number(),
  }).index("by_station_date", ["stationIcao", "date"]),

  weatherComPwsObservations: defineTable({
    stationIcao: v.string(),
    pwsStationId: v.string(),
    source: v.string(),
    keySource: v.string(),
    date: v.string(),
    obsTimeUtc: v.number(),
    obsTimeLocal: v.string(),
    neighborhood: v.optional(v.string()),
    softwareType: v.optional(v.string()),
    country: v.optional(v.string()),
    latitude: v.optional(v.number()),
    longitude: v.optional(v.number()),
    qcStatus: v.optional(v.number()),
    realtimeFrequency: v.optional(v.number()),
    solarRadiation: v.optional(v.number()),
    uv: v.optional(v.number()),
    relativeHumidity: v.optional(v.number()),
    windDirDegrees: v.optional(v.number()),
    tempC: v.optional(v.number()),
    tempF: v.optional(v.number()),
    dewpointC: v.optional(v.number()),
    dewpointF: v.optional(v.number()),
    heatIndexC: v.optional(v.number()),
    heatIndexF: v.optional(v.number()),
    windChillC: v.optional(v.number()),
    windChillF: v.optional(v.number()),
    windSpeedMph: v.optional(v.number()),
    windSpeedMps: v.optional(v.number()),
    windGustMph: v.optional(v.number()),
    windGustMps: v.optional(v.number()),
    pressureInHg: v.optional(v.number()),
    pressureHpa: v.optional(v.number()),
    precipRateIn: v.optional(v.number()),
    precipTotalIn: v.optional(v.number()),
    elevFt: v.optional(v.number()),
    firstSeenAt: v.number(),
    lastSeenAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_station_pws_date_ts", [
      "stationIcao",
      "pwsStationId",
      "date",
      "obsTimeUtc",
    ])
    .index("by_station_date_ts", ["stationIcao", "date", "obsTimeUtc"]),

  weatherComPwsDailySummaries: defineTable({
    stationIcao: v.string(),
    pwsStationId: v.string(),
    source: v.string(),
    keySource: v.string(),
    date: v.string(),
    obsCount: v.number(),
    latestObsTimeUtc: v.optional(v.number()),
    latestObsTimeLocal: v.optional(v.string()),
    latestTempC: v.optional(v.number()),
    latestTempF: v.optional(v.number()),
    latestQcStatus: v.optional(v.number()),
    latestNeighborhood: v.optional(v.string()),
    maxTempC: v.optional(v.number()),
    maxTempF: v.optional(v.number()),
    maxTempAtUtc: v.optional(v.number()),
    maxTempAtLocal: v.optional(v.string()),
    minTempC: v.optional(v.number()),
    minTempF: v.optional(v.number()),
    minTempAtUtc: v.optional(v.number()),
    minTempAtLocal: v.optional(v.string()),
    updatedAt: v.number(),
  })
    .index("by_station_pws_date", ["stationIcao", "pwsStationId", "date"])
    .index("by_station_date", ["stationIcao", "date"]),

  parisMeteoFranceObservations: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    obsTimeUtc: v.number(),
    obsTimeLocal: v.string(),
    tempC: v.number(),
    tempF: v.number(),
    dewpointC: v.optional(v.number()),
    humidity: v.optional(v.number()),
    windSpeedMps: v.optional(v.number()),
    windDirection: v.optional(v.number()),
    windGustMps: v.optional(v.number()),
    pressureHpa: v.optional(v.number()),
    visibility: v.optional(v.number()),
    source: v.string(),
    createdAt: v.number(),
  }).index("by_station_date_ts", ["stationIcao", "date", "obsTimeUtc"]),

  parisMeteoFranceHourlyForecasts: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    forecastTimeUtc: v.number(),
    forecastTimeLocal: v.string(),
    tempC: v.number(),
    tempF: v.number(),
    humidity: v.optional(v.number()),
    windSpeedMps: v.optional(v.number()),
    windDirection: v.optional(v.number()),
    windGustMps: v.optional(v.number()),
    cloudCover: v.optional(v.number()),
    weatherDescription: v.optional(v.string()),
    rain1h: v.optional(v.number()),
    capturedAt: v.number(),
  }).index("by_station_date_ts", ["stationIcao", "date", "forecastTimeUtc"]),

  aerowebMetarObservations: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    obsTimeUtc: v.number(),
    obsTimeLocal: v.string(),
    reportType: v.union(v.literal("METAR"), v.literal("SPECI")),
    tempC: v.number(),
    tempF: v.number(),
    rawMetar: v.string(),
    source: v.string(),
    aerowebFirstSeenAt: v.optional(v.number()),
    updatedAt: v.number(),
  }).index("by_station_date_ts", ["stationIcao", "date", "obsTimeUtc"]),

  aerowebDailySummaries: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    obsCount: v.number(),
    latestObsTimeUtc: v.optional(v.number()),
    latestObsTimeLocal: v.optional(v.string()),
    latestReportType: v.optional(v.string()),
    latestTempC: v.optional(v.number()),
    latestTempF: v.optional(v.number()),
    latestRawMetar: v.optional(v.string()),
    maxTempC: v.optional(v.number()),
    maxTempF: v.optional(v.number()),
    maxTempAtUtc: v.optional(v.number()),
    maxTempAtLocal: v.optional(v.string()),
    minTempC: v.optional(v.number()),
    minTempF: v.optional(v.number()),
    minTempAtUtc: v.optional(v.number()),
    minTempAtLocal: v.optional(v.string()),
    updatedAt: v.number(),
  }).index("by_station_date", ["stationIcao", "date"]),

  aerowebPublishRaceReports: defineTable({
    stationIcao: v.string(),
    reportDateLocal: v.string(),
    reportTsUtc: v.number(),
    reportType: v.optional(v.union(v.literal("METAR"), v.literal("SPECI"))),
    rawMetar: v.optional(v.string()),
    aerowebRawMetar: v.optional(v.string()),
    tgftpRawMetar: v.optional(v.string()),
    aerowebFirstSeenAt: v.optional(v.number()),
    tgftpFirstSeenAt: v.optional(v.number()),
    tgftpLastModifiedAt: v.optional(v.number()),
    winner: v.optional(
      v.union(v.literal("aeroweb"), v.literal("tgftp"), v.literal("tie")),
    ),
    leadMs: v.optional(v.number()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_station_reportTs", ["stationIcao", "reportTsUtc"]),

  preflightMetarObservations: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    obsTimeUtc: v.number(),
    obsTimeLocal: v.string(),
    reportType: v.union(v.literal("METAR"), v.literal("SPECI")),
    tempC: v.number(),
    tempF: v.number(),
    rawMetar: v.string(),
    source: v.string(),
    preflightFirstSeenAt: v.optional(v.number()),
    updatedAt: v.number(),
  }).index("by_station_date_ts", ["stationIcao", "date", "obsTimeUtc"]),

  preflightDailySummaries: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    obsCount: v.number(),
    latestObsTimeUtc: v.optional(v.number()),
    latestObsTimeLocal: v.optional(v.string()),
    latestReportType: v.optional(v.string()),
    latestTempC: v.optional(v.number()),
    latestTempF: v.optional(v.number()),
    latestRawMetar: v.optional(v.string()),
    maxTempC: v.optional(v.number()),
    maxTempF: v.optional(v.number()),
    maxTempAtUtc: v.optional(v.number()),
    maxTempAtLocal: v.optional(v.string()),
    minTempC: v.optional(v.number()),
    minTempF: v.optional(v.number()),
    minTempAtUtc: v.optional(v.number()),
    minTempAtLocal: v.optional(v.string()),
    updatedAt: v.number(),
  }).index("by_station_date", ["stationIcao", "date"]),

  preflightPublishRaceReports: defineTable({
    stationIcao: v.string(),
    reportDateLocal: v.string(),
    reportTsUtc: v.number(),
    reportType: v.optional(v.union(v.literal("METAR"), v.literal("SPECI"))),
    rawMetar: v.optional(v.string()),
    aerowebRawMetar: v.optional(v.string()),
    preflightRawMetar: v.optional(v.string()),
    tgftpRawMetar: v.optional(v.string()),
    aerowebFirstSeenAt: v.optional(v.number()),
    preflightFirstSeenAt: v.optional(v.number()),
    statusFirstSeenAt: v.optional(v.number()),
    tgftpFirstSeenAt: v.optional(v.number()),
    tgftpLastModifiedAt: v.optional(v.number()),
    winner: v.optional(
      v.union(
        v.literal("aeroweb"),
        v.literal("preflight"),
        v.literal("tgftp"),
        v.literal("tie"),
      ),
    ),
    leadMs: v.optional(v.number()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_station_reportTs", ["stationIcao", "reportTsUtc"]),

  madridMetarObservations: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    obsTimeUtc: v.number(),
    obsTimeLocal: v.string(),
    reportType: v.union(v.literal("METAR"), v.literal("SPECI")),
    tempC: v.number(),
    tempF: v.number(),
    rawMetar: v.string(),
    source: v.string(),
    aemetFirstSeenAt: v.optional(v.number()),
    updatedAt: v.number(),
  }).index("by_station_date_ts", ["stationIcao", "date", "obsTimeUtc"]),

  madridDailySummaries: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    obsCount: v.number(),
    latestObsTimeUtc: v.optional(v.number()),
    latestObsTimeLocal: v.optional(v.string()),
    latestReportType: v.optional(v.string()),
    latestTempC: v.optional(v.number()),
    latestTempF: v.optional(v.number()),
    latestRawMetar: v.optional(v.string()),
    maxTempC: v.optional(v.number()),
    maxTempF: v.optional(v.number()),
    maxTempAtUtc: v.optional(v.number()),
    maxTempAtLocal: v.optional(v.string()),
    minTempC: v.optional(v.number()),
    minTempF: v.optional(v.number()),
    minTempAtUtc: v.optional(v.number()),
    minTempAtLocal: v.optional(v.string()),
    updatedAt: v.number(),
  }).index("by_station_date", ["stationIcao", "date"]),

  madridPublishRaceReports: defineTable({
    stationIcao: v.string(),
    reportDateLocal: v.string(),
    reportTsUtc: v.number(),
    reportType: v.optional(v.union(v.literal("METAR"), v.literal("SPECI"))),
    rawMetar: v.optional(v.string()),
    aemetRawMetar: v.optional(v.string()),
    tgftpRawMetar: v.optional(v.string()),
    aemetFirstSeenAt: v.optional(v.number()),
    tgftpFirstSeenAt: v.optional(v.number()),
    tgftpLastModifiedAt: v.optional(v.number()),
    winner: v.optional(
      v.union(v.literal("aemet"), v.literal("tgftp"), v.literal("tie")),
    ),
    leadMs: v.optional(v.number()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_station_reportTs", ["stationIcao", "reportTsUtc"]),

  milanMetarObservations: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    obsTimeUtc: v.number(),
    obsTimeLocal: v.string(),
    reportType: v.union(v.literal("METAR"), v.literal("SPECI")),
    tempC: v.number(),
    tempF: v.number(),
    rawMetar: v.string(),
    source: v.string(),
    meteoAmFirstSeenAt: v.optional(v.number()),
    updatedAt: v.number(),
  }).index("by_station_date_ts", ["stationIcao", "date", "obsTimeUtc"]),

  milanDailySummaries: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    obsCount: v.number(),
    latestObsTimeUtc: v.optional(v.number()),
    latestObsTimeLocal: v.optional(v.string()),
    latestReportType: v.optional(v.string()),
    latestTempC: v.optional(v.number()),
    latestTempF: v.optional(v.number()),
    latestRawMetar: v.optional(v.string()),
    maxTempC: v.optional(v.number()),
    maxTempF: v.optional(v.number()),
    maxTempAtUtc: v.optional(v.number()),
    maxTempAtLocal: v.optional(v.string()),
    minTempC: v.optional(v.number()),
    minTempF: v.optional(v.number()),
    minTempAtUtc: v.optional(v.number()),
    minTempAtLocal: v.optional(v.string()),
    updatedAt: v.number(),
  }).index("by_station_date", ["stationIcao", "date"]),

  milanPublishRaceReports: defineTable({
    stationIcao: v.string(),
    reportDateLocal: v.string(),
    reportTsUtc: v.number(),
    reportType: v.optional(v.union(v.literal("METAR"), v.literal("SPECI"))),
    rawMetar: v.optional(v.string()),
    meteoAmRawMetar: v.optional(v.string()),
    tgftpRawMetar: v.optional(v.string()),
    meteoAmFirstSeenAt: v.optional(v.number()),
    tgftpFirstSeenAt: v.optional(v.number()),
    tgftpLastModifiedAt: v.optional(v.number()),
    winner: v.optional(
      v.union(v.literal("meteoam"), v.literal("tgftp"), v.literal("tie")),
    ),
    leadMs: v.optional(v.number()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_station_reportTs", ["stationIcao", "reportTsUtc"]),

  madridAemetHourlyForecasts: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    forecastTimeUtc: v.number(),
    forecastTimeLocal: v.string(),
    tempC: v.number(),
    tempF: v.number(),
    humidity: v.optional(v.number()),
    windSpeedKph: v.optional(v.number()),
    windDirection: v.optional(v.string()),
    skyDescription: v.optional(v.string()),
    precipitation: v.optional(v.number()),
    capturedAt: v.number(),
  }).index("by_station_date_ts", ["stationIcao", "date", "forecastTimeUtc"]),

  madridAemetStationObservations: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    obsTimeUtc: v.number(),
    obsTimeLocal: v.string(),
    tempC: v.number(),
    tempF: v.number(),
    humidity: v.optional(v.number()),
    dewPointC: v.optional(v.number()),
    windSpeedKmh: v.optional(v.number()),
    windDirection: v.optional(v.number()),
    pressureHpa: v.optional(v.number()),
    precipMm: v.optional(v.number()),
    source: v.string(),
    capturedAt: v.number(),
  }).index("by_station_date_ts", ["stationIcao", "date", "obsTimeUtc"]),

  madridSynopObservations: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    obsTimeUtc: v.number(),
    obsTimeLocal: v.string(),
    tempC: v.number(),
    tempF: v.number(),
    dewPointC: v.optional(v.number()),
    rawSynop: v.string(),
    source: v.string(),
    capturedAt: v.number(),
  }).index("by_station_date_ts", ["stationIcao", "date", "obsTimeUtc"]),

  nzwnMetServiceObservations: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    obsTimeUtc: v.number(),
    obsTimeLocal: v.string(),
    tempC: v.number(),
    tempF: v.number(),
    relativeHumidity: v.optional(v.number()),
    windSpeedKph: v.optional(v.number()),
    windGustKph: v.optional(v.number()),
    windDirection: v.optional(v.string()),
    pressureHpa: v.optional(v.number()),
    source: v.string(),
    createdAt: v.number(),
  }).index("by_station_date_ts", ["stationIcao", "date", "obsTimeUtc"]),

  nzwnMetServiceHourlyForecasts: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    forecastTimeUtc: v.number(),
    forecastTimeLocal: v.string(),
    tempC: v.number(),
    tempF: v.number(),
    windSpeedKph: v.optional(v.number()),
    windDirection: v.optional(v.string()),
    rainfall: v.optional(v.number()),
    capturedAt: v.number(),
  }).index("by_station_date_ts", ["stationIcao", "date", "forecastTimeUtc"]),

  nzwnForecastPredictions: defineTable({
    stationIcao: v.string(),
    provider: v.literal("metservice"),
    targetDate: v.string(),
    capturedAt: v.number(),
    capturedAtLocal: v.string(),
    captureDate: v.string(),
    leadDays: v.number(),
    minTempC: v.optional(v.number()),
    minTempF: v.optional(v.number()),
    maxTempC: v.optional(v.number()),
    maxTempF: v.optional(v.number()),
    dayPhrase: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_station_provider_target_capturedAt", [
      "stationIcao",
      "provider",
      "targetDate",
      "capturedAt",
    ])
    .index("by_station_captureDate", ["stationIcao", "captureDate"]),

  nzwnDailySummaries: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    obsCount: v.number(),
    maxTempC: v.optional(v.number()),
    maxTempF: v.optional(v.number()),
    maxTempAtUtc: v.optional(v.number()),
    maxTempAtLocal: v.optional(v.string()),
    minTempC: v.optional(v.number()),
    minTempF: v.optional(v.number()),
    minTempAtUtc: v.optional(v.number()),
    minTempAtLocal: v.optional(v.string()),
    latestObsTimeUtc: v.optional(v.number()),
    latestObsTimeLocal: v.optional(v.string()),
    updatedAt: v.number(),
  }).index("by_station_date", ["stationIcao", "date"]),

  ankaraMetarObservations: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    obsTimeUtc: v.number(),
    obsTimeLocal: v.string(),
    reportType: v.union(v.literal("METAR"), v.literal("SPECI")),
    tempC: v.number(),
    tempF: v.number(),
    rawMetar: v.string(),
    source: v.string(),
    mgmFirstSeenAt: v.optional(v.number()),
    updatedAt: v.number(),
  }).index("by_station_date_ts", ["stationIcao", "date", "obsTimeUtc"]),

  ankaraDailySummaries: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    obsCount: v.number(),
    latestObsTimeUtc: v.optional(v.number()),
    latestObsTimeLocal: v.optional(v.string()),
    latestReportType: v.optional(v.string()),
    latestTempC: v.optional(v.number()),
    latestTempF: v.optional(v.number()),
    latestRawMetar: v.optional(v.string()),
    maxTempC: v.optional(v.number()),
    maxTempF: v.optional(v.number()),
    maxTempAtUtc: v.optional(v.number()),
    maxTempAtLocal: v.optional(v.string()),
    minTempC: v.optional(v.number()),
    minTempF: v.optional(v.number()),
    minTempAtUtc: v.optional(v.number()),
    minTempAtLocal: v.optional(v.string()),
    updatedAt: v.number(),
  }).index("by_station_date", ["stationIcao", "date"]),

  ankaraPublishRaceReports: defineTable({
    stationIcao: v.string(),
    reportDateLocal: v.string(),
    reportTsUtc: v.number(),
    reportType: v.optional(v.union(v.literal("METAR"), v.literal("SPECI"))),
    rawMetar: v.optional(v.string()),
    mgmRawMetar: v.optional(v.string()),
    tgftpRawMetar: v.optional(v.string()),
    mgmFirstSeenAt: v.optional(v.number()),
    tgftpFirstSeenAt: v.optional(v.number()),
    tgftpLastModifiedAt: v.optional(v.number()),
    winner: v.optional(
      v.union(v.literal("mgm"), v.literal("tgftp"), v.literal("tie")),
    ),
    leadMs: v.optional(v.number()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_station_reportTs", ["stationIcao", "reportTsUtc"]),

  ankaraMgmObservations: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    obsTimeUtc: v.number(),
    obsTimeLocal: v.string(),
    tempC: v.number(),
    tempF: v.number(),
    humidity: v.optional(v.number()),
    windSpeedMps: v.optional(v.number()),
    windDirection: v.optional(v.number()),
    visibility: v.optional(v.number()),
    pressureHpa: v.optional(v.number()),
    cloudCover: v.optional(v.number()),
    source: v.string(),
    createdAt: v.number(),
  }).index("by_station_date_ts", ["stationIcao", "date", "obsTimeUtc"]),

  ankaraMgmHourlyForecasts: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    forecastTimeUtc: v.number(),
    forecastTimeLocal: v.string(),
    tempC: v.number(),
    tempF: v.number(),
    humidity: v.optional(v.number()),
    windSpeedKph: v.optional(v.number()),
    windDirection: v.optional(v.number()),
    weatherCode: v.optional(v.string()),
    capturedAt: v.number(),
  }).index("by_station_date_ts", ["stationIcao", "date", "forecastTimeUtc"]),

  seoulMetarObservations: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    obsTimeUtc: v.number(),
    obsTimeLocal: v.string(),
    reportType: v.union(v.literal("METAR"), v.literal("SPECI")),
    tempC: v.number(),
    tempF: v.number(),
    rawMetar: v.string(),
    source: v.string(),
    amoFirstSeenAt: v.optional(v.number()),
    updatedAt: v.number(),
  }).index("by_station_date_ts", ["stationIcao", "date", "obsTimeUtc"]),

  seoulDailySummaries: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    obsCount: v.number(),
    latestObsTimeUtc: v.optional(v.number()),
    latestObsTimeLocal: v.optional(v.string()),
    latestReportType: v.optional(v.string()),
    latestTempC: v.optional(v.number()),
    latestTempF: v.optional(v.number()),
    latestRawMetar: v.optional(v.string()),
    maxTempC: v.optional(v.number()),
    maxTempF: v.optional(v.number()),
    maxTempAtUtc: v.optional(v.number()),
    maxTempAtLocal: v.optional(v.string()),
    minTempC: v.optional(v.number()),
    minTempF: v.optional(v.number()),
    minTempAtUtc: v.optional(v.number()),
    minTempAtLocal: v.optional(v.string()),
    updatedAt: v.number(),
  }).index("by_station_date", ["stationIcao", "date"]),

  seoulAmosObservations: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    obsTimeUtc: v.number(),
    obsTimeLocal: v.string(),
    collectionCadence: v.optional(
      v.union(v.literal("one_minute"), v.literal("five_minute")),
    ),
    rwyNo: v.string(),
    rwyDir: v.string(),
    rwyUse: v.optional(v.string()),
    rwyMain: v.optional(v.string()),
    tempC: v.optional(v.number()),
    tempF: v.optional(v.number()),
    dewpointC: v.optional(v.number()),
    dewpointF: v.optional(v.number()),
    qnhHpa: v.optional(v.number()),
    qnhInHg: v.optional(v.number()),
    windDirAvg: v.optional(v.number()),
    windDirMin: v.optional(v.number()),
    windDirMax: v.optional(v.number()),
    windSpeedAvg: v.optional(v.number()),
    windSpeedMin: v.optional(v.number()),
    windSpeedMax: v.optional(v.number()),
    crosswind: v.optional(v.string()),
    headtail: v.optional(v.string()),
    morMeters: v.optional(v.number()),
    rvrMeters: v.optional(v.string()),
    precipMm: v.optional(v.number()),
    source: v.string(),
    rawJson: v.optional(v.string()),
    updatedAt: v.number(),
  })
    .index("by_station_date_ts_rwy", [
      "stationIcao",
      "date",
      "obsTimeUtc",
      "rwyNo",
      "rwyDir",
    ])
    .index("by_station_date_ts_rwy_cadence", [
      "stationIcao",
      "date",
      "obsTimeUtc",
      "rwyNo",
      "rwyDir",
      "collectionCadence",
    ])
    .index("by_station_date_rwy_ts", [
      "stationIcao",
      "date",
      "rwyNo",
      "rwyDir",
      "obsTimeUtc",
    ]),

  seoulForecastCaptures: defineTable({
    stationIcao: v.string(),
    stationName: v.string(),
    capturedAt: v.number(),
    capturedAtLocal: v.string(),
    captureDate: v.string(),
    status: seoulForecastStatus,
    weathercomStatus: seoulProviderStatus,
    weathercomError: v.optional(v.string()),
    weathercomForecastDays: v.array(
      v.object({
        date: v.string(),
        minTempC: v.optional(v.number()),
        minTempF: v.optional(v.number()),
        maxTempC: v.optional(v.number()),
        maxTempF: v.optional(v.number()),
        dayPhrase: v.optional(v.string()),
        nightPhrase: v.optional(v.string()),
      }),
    ),
    weathercomHourlyStatus: v.optional(seoulProviderStatus),
    weathercomHourlyError: v.optional(v.string()),
    weathercomHourlyCapturedAt: v.optional(v.number()),
    weathercomHourlyCapturedAtLocal: v.optional(v.string()),
    weathercomHourlyCaptureDate: v.optional(v.string()),
    weathercomHourlyRows: v.optional(v.array(seoulHourlyForecastRow)),
    googleStatus: v.optional(seoulProviderStatus),
    googleError: v.optional(v.string()),
    googleHourlyRows: v.optional(v.array(seoulHourlyForecastRow)),
    openMeteoStatus: v.optional(seoulProviderStatus),
    openMeteoError: v.optional(v.string()),
    openMeteoHourlyRows: v.optional(v.array(seoulHourlyForecastRow)),
    createdAt: v.number(),
  }).index("by_station_capturedAt", ["stationIcao", "capturedAt"]),

  seoulHourlyForecastPredictions: defineTable({
    stationIcao: v.string(),
    provider: v.literal("weathercom"),
    targetDate: v.string(),
    forecastTimeUtc: v.number(),
    forecastTimeLocal: v.string(),
    capturedAt: v.number(),
    capturedAtLocal: v.string(),
    captureDate: v.string(),
    tempC: v.number(),
    tempF: v.number(),
    phrase: v.optional(v.string()),
    cloudCoverPct: v.optional(v.number()),
    forecastCaptureId: v.id("seoulForecastCaptures"),
    createdAt: v.number(),
  })
    .index("by_station_provider_target_capturedAt", [
      "stationIcao",
      "provider",
      "targetDate",
      "capturedAt",
    ])
    .index("by_station_provider_valid_capturedAt", [
      "stationIcao",
      "provider",
      "forecastTimeUtc",
      "capturedAt",
    ])
    .index("by_forecast_capture_id", ["forecastCaptureId"]),

  seoulAmosDailySummaries: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    rwyNo: v.literal("2"),
    rwyDir: v.literal("15L"),
    obsCount: v.number(),
    oneMinuteObsCount: v.number(),
    fallbackObsCount: v.number(),
    firstObsTimeUtc: v.optional(v.number()),
    firstObsTimeLocal: v.optional(v.string()),
    latestObsTimeUtc: v.optional(v.number()),
    latestObsTimeLocal: v.optional(v.string()),
    latestTempC: v.optional(v.number()),
    latestTempF: v.optional(v.number()),
    maxTempC: v.optional(v.number()),
    maxTempF: v.optional(v.number()),
    maxTempAtUtc: v.optional(v.number()),
    maxTempAtLocal: v.optional(v.string()),
    minTempC: v.optional(v.number()),
    minTempF: v.optional(v.number()),
    minTempAtUtc: v.optional(v.number()),
    minTempAtLocal: v.optional(v.string()),
    updatedAt: v.number(),
  }).index("by_station_date", ["stationIcao", "date"]),

  seoulHighPredictions: defineTable({
    stationIcao: v.string(),
    targetDate: v.string(),
    revision: v.number(),
    evaluationSlotUtc: v.number(),
    modelVersion: v.string(),
    generatedAt: v.number(),
    generatedAtLocal: v.string(),
    forecastCaptureId: v.optional(v.id("seoulForecastCaptures")),
    forecastCapturedAt: v.optional(v.number()),
    forecastAgeMinutes: v.optional(v.number()),
    previousPredictionId: v.optional(v.id("seoulHighPredictions")),
    observedCount: v.number(),
    observedCurrentC: v.optional(v.number()),
    observedCurrentF: v.optional(v.number()),
    observedCurrentAtUtc: v.optional(v.number()),
    observedCurrentAtLocal: v.optional(v.string()),
    observationAgeMinutes: v.optional(v.number()),
    observedHighC: v.optional(v.number()),
    observedHighF: v.optional(v.number()),
    observedHighAtUtc: v.optional(v.number()),
    observedHighAtLocal: v.optional(v.string()),
    slope15mCPerHour: v.optional(v.number()),
    slope30mCPerHour: v.optional(v.number()),
    slope60mCPerHour: v.optional(v.number()),
    expectedCurrentC: v.optional(v.number()),
    liveBiasC: v.optional(v.number()),
    predictedHighC: v.number(),
    predictedHighF: v.number(),
    confidenceLowC: v.number(),
    confidenceLowF: v.number(),
    confidenceHighC: v.number(),
    confidenceHighF: v.number(),
    peakWindowStartUtc: v.optional(v.number()),
    peakWindowEndUtc: v.optional(v.number()),
    peakWindowStartLocal: v.optional(v.string()),
    peakWindowEndLocal: v.optional(v.string()),
    status: seoulPredictionStatus,
    reason: v.string(),
    providerDetails: v.array(seoulProviderDetail),
    hourlyEnsembleCurve: v.array(
      v.object({
        forecastTimeUtc: v.number(),
        forecastTimeLocal: v.string(),
        tempC: v.number(),
        tempF: v.number(),
        providerCount: v.number(),
        cloudCoverPct: v.optional(v.number()),
        cloudProviderCount: v.optional(v.number()),
      }),
    ),
    createdAt: v.number(),
  })
    .index("by_station_date_revision", [
      "stationIcao",
      "targetDate",
      "revision",
    ])
    .index("by_station_date_generatedAt", [
      "stationIcao",
      "targetDate",
      "generatedAt",
    ])
    .index("by_station_date_slot", [
      "stationIcao",
      "targetDate",
      "evaluationSlotUtc",
    ]),

  seoulHighEvaluations: defineTable({
    stationIcao: v.string(),
    targetDate: v.string(),
    finalizedAt: v.number(),
    finalizedAtLocal: v.string(),
    actualHighC: v.number(),
    actualHighF: v.number(),
    actualHighAtUtc: v.number(),
    actualHighAtLocal: v.string(),
    obsCount: v.number(),
    initialPredictionId: v.optional(v.id("seoulHighPredictions")),
    initialPredictedHighC: v.optional(v.number()),
    initialPredictedHighF: v.optional(v.number()),
    initialErrorC: v.optional(v.number()),
    initialAbsoluteErrorC: v.optional(v.number()),
    finalPredictionId: v.optional(v.id("seoulHighPredictions")),
    finalPredictedHighC: v.optional(v.number()),
    finalPredictedHighF: v.optional(v.number()),
    finalErrorC: v.optional(v.number()),
    finalAbsoluteErrorC: v.optional(v.number()),
    finalPeakWindowStartUtc: v.optional(v.number()),
    finalPeakWindowEndUtc: v.optional(v.number()),
    peakWindowHit: v.optional(v.boolean()),
    checkpoints: v.optional(
      v.array(
        v.object({
          localHour: v.number(),
          cutoffAtUtc: v.number(),
          cutoffAtLocal: v.string(),
          predictionId: v.optional(v.id("seoulHighPredictions")),
          predictedHighC: v.optional(v.number()),
          predictedHighF: v.optional(v.number()),
          errorC: v.optional(v.number()),
          absoluteErrorC: v.optional(v.number()),
          peakWindowStartUtc: v.optional(v.number()),
          peakWindowEndUtc: v.optional(v.number()),
          peakWindowHit: v.optional(v.boolean()),
        }),
      ),
    ),
    revisionCount: v.number(),
    createdAt: v.number(),
  })
    .index("by_station_date", ["stationIcao", "targetDate"])
    .index("by_station_finalizedAt", ["stationIcao", "finalizedAt"]),

  seoulPublishRaceReports: defineTable({
    stationIcao: v.string(),
    reportDateLocal: v.string(),
    reportTsUtc: v.number(),
    reportType: v.optional(v.union(v.literal("METAR"), v.literal("SPECI"))),
    rawMetar: v.optional(v.string()),
    amoRawMetar: v.optional(v.string()),
    tgftpRawMetar: v.optional(v.string()),
    amoFirstSeenAt: v.optional(v.number()),
    tgftpFirstSeenAt: v.optional(v.number()),
    tgftpLastModifiedAt: v.optional(v.number()),
    winner: v.optional(
      v.union(v.literal("amo"), v.literal("tgftp"), v.literal("tie")),
    ),
    leadMs: v.optional(v.number()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_station_reportTs", ["stationIcao", "reportTsUtc"]),
});
