//convex/schema.js
import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

const seoulForecastStatus = v.union(
  v.literal("ok"),
  v.literal("partial"),
  v.literal("error"),
);

const seoulProviderStatus = v.union(v.literal("ok"), v.literal("error"));

const seoulKmaForecastCaptureStatus = v.union(
  v.literal("ok"),
  v.literal("error"),
  v.literal("approval_required"),
);

const seoulKmaForecastCollectorStatus = v.union(
  v.literal("queued"),
  v.literal("ok"),
  v.literal("error"),
  v.literal("approval_required"),
);

const seoulGk2aCollectorStatus = v.union(
  v.literal("ok"),
  v.literal("partial"),
  v.literal("no_data"),
  v.literal("error"),
  v.literal("unconfigured"),
);

const seoulGk2aPointKind = v.union(
  v.literal("airport"),
  v.literal("upwind_20m"),
  v.literal("upwind_40m"),
  v.literal("upwind_60m"),
);

const seoulHourlyForecastRow = v.object({
  date: v.string(),
  forecastTimeUtc: v.number(),
  forecastTimeLocal: v.string(),
  tempC: v.number(),
  tempF: v.number(),
  phrase: v.optional(v.string()),
  cloudCoverPct: v.optional(v.number()),
});

const seoulProviderDetail = v.object({
  provider: v.union(
    v.literal("kma_amo"),
    v.literal("weathercom"),
    v.literal("google"),
    v.literal("open_meteo"),
  ),
  label: v.string(),
  role: v.optional(v.union(v.literal("primary"), v.literal("secondary"))),
  sourceUrl: v.optional(v.string()),
  status: seoulProviderStatus,
  error: v.optional(v.string()),
  weight: v.number(),
  rawHighC: v.optional(v.number()),
  rawHighF: v.optional(v.number()),
  adjustedHighC: v.optional(v.number()),
  adjustedHighF: v.optional(v.number()),
  dailyHighC: v.optional(v.number()),
  dailyHighF: v.optional(v.number()),
  dailyPeakTimeUtc: v.optional(v.number()),
  dailyPeakTimeLocal: v.optional(v.string()),
  liveBiasC: v.optional(v.number()),
  capturedAt: v.optional(v.number()),
  capturedAtLocal: v.optional(v.string()),
  captureAgeMinutes: v.optional(v.number()),
  peakTimeUtc: v.optional(v.number()),
  peakTimeLocal: v.optional(v.string()),
  peakSourceCapturedAt: v.optional(v.number()),
  peakSourceCapturedAtLocal: v.optional(v.string()),
  pointCount: v.number(),
});

const seoulPredictionStatus = v.union(
  v.literal("awaiting_observations"),
  v.literal("on_track"),
  v.literal("running_warm"),
  v.literal("running_cool"),
  v.literal("limited_guidance"),
  v.literal("revised_up"),
  v.literal("revised_down"),
  v.literal("peak_likely_passed"),
  v.literal("final"),
);

const seoulPeakDecisionStatus = v.union(
  v.literal("already_reached"),
  v.literal("insufficient_data"),
  v.literal("still_possible"),
  v.literal("peak_candidate"),
  v.literal("unlikely_to_reach"),
  v.literal("final"),
);

const seoulSolarTrendStatus = v.union(
  v.literal("increasing"),
  v.literal("decreasing"),
  v.literal("steady"),
  v.literal("unavailable"),
);

const seoulSolarUpwindSignal = v.union(
  v.literal("clearing"),
  v.literal("cloudier"),
  v.literal("similar"),
  v.literal("unavailable"),
);

const mexicoEdgeMarketDefinition = v.object({
  marketId: v.string(),
  marketSlug: v.string(),
  conditionId: v.string(),
  label: v.string(),
  displayOrder: v.number(),
  sourceIndex: v.number(),
  yesTokenId: v.string(),
  noTokenId: v.optional(v.string()),
  gammaOutcomePrice: v.optional(v.string()),
  gammaProbabilityPct: v.optional(v.number()),
  enableOrderBook: v.boolean(),
  negRisk: v.boolean(),
  question: v.optional(v.string()),
  description: v.optional(v.string()),
  resolutionSource: v.optional(v.string()),
});

const mexicoEdgeQuoteFields = {
  stationIcao: v.string(),
  date: v.string(),
  source: v.string(),
  eventId: v.string(),
  marketId: v.string(),
  marketSlug: v.string(),
  conditionId: v.string(),
  label: v.string(),
  yesTokenId: v.string(),
  displayOrder: v.number(),
  gammaOutcomePrice: v.optional(v.string()),
  gammaProbabilityPct: v.optional(v.number()),
  bookAvailable: v.boolean(),
  bestBidPrice: v.optional(v.string()),
  bestBidSize: v.optional(v.string()),
  bestAskPrice: v.optional(v.string()),
  bestAskSize: v.optional(v.string()),
  midpointPrice: v.optional(v.string()),
  spreadPrice: v.optional(v.string()),
  lastTradePrice: v.optional(v.string()),
  lastTradeSide: v.optional(v.string()),
  lastTradeStatus: v.optional(
    v.union(v.literal("reported"), v.literal("no_trades")),
  ),
  platformDisplayPrice: v.optional(v.string()),
  platformDisplayProbabilityPct: v.optional(v.number()),
  platformDisplaySource: v.string(),
  tickSize: v.optional(v.string()),
  minOrderSize: v.optional(v.string()),
  bookHash: v.optional(v.string()),
  bookTimestamp: v.optional(v.number()),
  gammaReceivedAt: v.optional(v.number()),
  bookFetchStartedAt: v.optional(v.number()),
  bookReceivedAt: v.optional(v.number()),
  lastTradeFetchStartedAt: v.optional(v.number()),
  lastTradeReceivedAt: v.optional(v.number()),
  negRisk: v.boolean(),
  quoteFingerprint: v.string(),
  fetchedAt: v.number(),
  receivedAt: v.number(),
  lastChangedAt: v.number(),
  updatedAt: v.number(),
  createdAt: v.number(),
};

export default defineSchema({
  notes: defineTable({
    stationIcao: v.optional(v.string()),
    title: v.optional(v.string()),
    body: v.optional(v.string()),
    imageIds: v.array(v.id("_storage")),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_createdAt", ["createdAt"]),

  monthRuns: defineTable({
    stationIcao: v.string(),
    stationIem: v.string(),
    year: v.number(),
    month: v.number(),
    manualUnit: v.union(v.literal("C"), v.literal("F")),
    createdAt: v.number(),
    updatedAt: v.number(),
    metarLastComputedAt: v.optional(v.number()),
    metarLastStatus: v.union(
      v.literal("idle"),
      v.literal("computing"),
      v.literal("ok"),
      v.literal("error"),
    ),
    metarLastError: v.optional(v.string()),
    metarAllLastComputedAt: v.optional(v.number()),
    metarAllLastStatus: v.optional(
      v.union(
        v.literal("idle"),
        v.literal("computing"),
        v.literal("ok"),
        v.literal("error"),
      ),
    ),
    metarAllLastError: v.optional(v.string()),
  }).index("by_station_month", ["stationIcao", "year", "month"]),

  dailyComparisons: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    manualMaxC: v.optional(v.number()),
    manualMaxF: v.optional(v.number()),
    manualNotes: v.optional(v.string()),
    metarMaxC: v.optional(v.number()),
    metarMaxF: v.optional(v.number()),
    metarMaxAtUtc: v.optional(v.number()),
    metarMaxAtLocal: v.optional(v.string()),
    metarObsCount: v.optional(v.number()),
    metarMaxRaw: v.optional(v.string()),
    metarMaxSource: v.optional(v.string()),
    deltaC: v.optional(v.number()),
    deltaF: v.optional(v.number()),
    metarAllMaxC: v.optional(v.number()),
    metarAllMaxF: v.optional(v.number()),
    metarAllMaxAtUtc: v.optional(v.number()),
    metarAllMaxAtLocal: v.optional(v.string()),
    metarAllObsCount: v.optional(v.number()),
    metarAllMaxRaw: v.optional(v.string()),
    metarAllMaxSource: v.optional(v.string()),
    deltaAllC: v.optional(v.number()),
    deltaAllF: v.optional(v.number()),
    updatedAt: v.number(),
  }).index("by_station_date", ["stationIcao", "date"]),

  kordPhoneCalls: defineTable({
    stationIcao: v.string(),
    date: v.string(), // YYYY-MM-DD (Chicago)
    slotLocal: v.string(), // YYYY-MM-DD HH:MM (Chicago) scheduled slot or manual trigger time
    tsUtc: v.optional(v.number()), // recording start (ms epoch)
    tsLocal: v.optional(v.string()), // YYYY-MM-DD HH:MM (Chicago), derived from tsUtc
    callSid: v.optional(v.string()),
    recordingSid: v.optional(v.string()),
    recordingUrl: v.optional(v.string()),
    recordingDuration: v.optional(v.number()),
    transcript: v.optional(v.string()),
    tempC: v.optional(v.number()),
    tempF: v.optional(v.number()),
    status: v.union(
      v.literal("queued"),
      v.literal("calling"),
      v.literal("recorded"),
      v.literal("transcribed"),
      v.literal("parsed"),
      v.literal("error"),
    ),
    error: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_station_date", ["stationIcao", "date"])
    .index("by_station_slot", ["stationIcao", "slotLocal"])
    .index("by_callSid", ["callSid"]),

  kordForecastSnapshots: defineTable({
    stationIcao: v.string(),
    stationName: v.string(),
    capturedAt: v.number(),
    capturedAtLocal: v.string(),
    durationDays: v.number(),
    unit: v.union(v.literal("imperial"), v.literal("metric")),
    language: v.string(),
    status: v.union(v.literal("ok"), v.literal("partial"), v.literal("error")),
    microsoftStatus: v.union(v.literal("ok"), v.literal("error")),
    microsoftError: v.optional(v.string()),
    microsoftForecastDays: v.array(
      v.object({
        date: v.string(),
        minTempC: v.optional(v.number()),
        minTempF: v.optional(v.number()),
        maxTempC: v.optional(v.number()),
        maxTempF: v.optional(v.number()),
        dayPhrase: v.optional(v.string()),
        nightPhrase: v.optional(v.string()),
      }),
    ),
    accuweatherStatus: v.optional(v.union(v.literal("ok"), v.literal("error"))),
    accuweatherError: v.optional(v.string()),
    accuweatherLocationKey: v.optional(v.string()),
    accuweatherForecastDays: v.optional(
      v.array(
        v.object({
          date: v.string(),
          minTempC: v.optional(v.number()),
          minTempF: v.optional(v.number()),
          maxTempC: v.optional(v.number()),
          maxTempF: v.optional(v.number()),
          dayPhrase: v.optional(v.string()),
          nightPhrase: v.optional(v.string()),
        }),
      ),
    ),
    googleStatus: v.optional(v.union(v.literal("ok"), v.literal("error"))),
    googleError: v.optional(v.string()),
    googleForecastDays: v.optional(
      v.array(
        v.object({
          date: v.string(),
          minTempC: v.optional(v.number()),
          minTempF: v.optional(v.number()),
          maxTempC: v.optional(v.number()),
          maxTempF: v.optional(v.number()),
          dayPhrase: v.optional(v.string()),
          nightPhrase: v.optional(v.string()),
        }),
      ),
    ),
    weathercomStatus: v.optional(v.union(v.literal("ok"), v.literal("error"))),
    weathercomError: v.optional(v.string()),
    weathercomForecastDays: v.optional(
      v.array(
        v.object({
          date: v.string(),
          minTempC: v.optional(v.number()),
          minTempF: v.optional(v.number()),
          maxTempC: v.optional(v.number()),
          maxTempF: v.optional(v.number()),
          dayPhrase: v.optional(v.string()),
          nightPhrase: v.optional(v.string()),
        }),
      ),
    ),
    actualReadings: v.array(
      v.object({
        source: v.string(),
        status: v.union(v.literal("ok"), v.literal("error")),
        observedAtUtc: v.optional(v.number()),
        observedAtLocal: v.optional(v.string()),
        tempC: v.optional(v.number()),
        tempF: v.optional(v.number()),
        raw: v.optional(v.string()),
        error: v.optional(v.string()),
      }),
    ),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_station_capturedAt", ["stationIcao", "capturedAt"]),

  kordCurrentSnapshots: defineTable({
    stationIcao: v.string(),
    stationName: v.string(),
    capturedAt: v.number(),
    capturedAtLocal: v.string(),
    unit: v.union(v.literal("imperial"), v.literal("metric")),
    language: v.string(),
    status: v.union(v.literal("ok"), v.literal("partial"), v.literal("error")),
    actualReadings: v.array(
      v.object({
        source: v.string(),
        status: v.union(v.literal("ok"), v.literal("error")),
        observedAtUtc: v.optional(v.number()),
        observedAtLocal: v.optional(v.string()),
        tempC: v.optional(v.number()),
        tempF: v.optional(v.number()),
        raw: v.optional(v.string()),
        error: v.optional(v.string()),
      }),
    ),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_station_capturedAt", ["stationIcao", "capturedAt"]),

  kordForecastPredictions: defineTable({
    stationIcao: v.string(),
    provider: v.union(
      v.literal("microsoft"),
      v.literal("accuweather"),
      v.literal("google"),
      v.literal("weathercom"),
    ),
    targetDate: v.string(),
    capturedAt: v.number(),
    capturedAtLocal: v.string(),
    captureDate: v.string(),
    leadDays: v.number(),
    minTempC: v.optional(v.number()),
    minTempF: v.optional(v.number()),
    maxTempC: v.optional(v.number()),
    maxTempF: v.optional(v.number()),
    dayPhrase: v.optional(v.string()),
    nightPhrase: v.optional(v.string()),
    snapshotId: v.id("kordForecastSnapshots"),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_station_provider_target_capturedAt", [
      "stationIcao",
      "provider",
      "targetDate",
      "capturedAt",
    ])
    .index("by_snapshotId", ["snapshotId"]),

  metarObservations: defineTable({
    stationIcao: v.string(),
    mode: v.union(v.literal("official"), v.literal("all")),
    date: v.string(),
    tsUtc: v.number(),
    tsLocal: v.string(),
    tempC: v.optional(v.number()),
    tempF: v.optional(v.number()),
    rawMetar: v.string(),
    source: v.string(),
    noaaFirstSeenAt: v.optional(v.number()),
    updatedAt: v.number(),
  }).index("by_station_mode_date_ts", ["stationIcao", "mode", "date", "tsUtc"]),

  synopticObservations: defineTable({
    stationIcao: v.string(),
    provider: v.string(),
    source: v.string(),
    date: v.string(),
    obsTimeUtc: v.number(),
    obsTimeLocal: v.string(),
    tempC: v.optional(v.number()),
    tempF: v.optional(v.number()),
    dewpointC: v.optional(v.number()),
    dewpointF: v.optional(v.number()),
    relativeHumidity: v.optional(v.number()),
    windDirDegrees: v.optional(v.number()),
    windSpeedMph: v.optional(v.number()),
    windSpeedMps: v.optional(v.number()),
    visibilityMiles: v.optional(v.number()),
    ceilingFt: v.optional(v.number()),
    altimeterInHg: v.optional(v.number()),
    seaLevelPressureMb: v.optional(v.number()),
    weatherCondition: v.optional(v.string()),
    weatherSummary: v.optional(v.string()),
    metarOrigin: v.optional(v.string()),
    rawMetar: v.optional(v.string()),
    firstSeenAt: v.number(),
    lastSeenAt: v.number(),
    updatedAt: v.number(),
  }).index("by_station_date_ts", ["stationIcao", "date", "obsTimeUtc"]),

  synopticDailySummaries: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    obsCount: v.number(),
    latestObsTimeUtc: v.optional(v.number()),
    latestObsTimeLocal: v.optional(v.string()),
    lastResolvedFrameTimeUtc: v.optional(v.number()),
    latestRawMetar: v.optional(v.string()),
    latestMetarOrigin: v.optional(v.string()),
    maxTempC: v.optional(v.number()),
    maxTempF: v.optional(v.number()),
    maxTempAtUtc: v.optional(v.number()),
    maxTempAtLocal: v.optional(v.string()),
    minTempC: v.optional(v.number()),
    minTempF: v.optional(v.number()),
    minTempAtUtc: v.optional(v.number()),
    minTempAtLocal: v.optional(v.string()),
    updatedAt: v.number(),
  }).index("by_station_date", ["stationIcao", "date"]),

  madisHfmObservations: defineTable({
    stationIcao: v.string(),
    provider: v.string(),
    source: v.string(),
    date: v.string(),
    obsTimeUtc: v.number(),
    obsTimeLocal: v.string(),
    tempC: v.optional(v.number()),
    tempF: v.optional(v.number()),
    dewpointC: v.optional(v.number()),
    dewpointF: v.optional(v.number()),
    relativeHumidity: v.optional(v.number()),
    windDirDegrees: v.optional(v.number()),
    windSpeedMps: v.optional(v.number()),
    windGustMps: v.optional(v.number()),
    altimeterPa: v.optional(v.number()),
    dewpointQcd: v.optional(v.string()),
    relativeHumidityQcd: v.optional(v.string()),
    tempQcd: v.optional(v.string()),
    windDirQcd: v.optional(v.string()),
    windSpeedQcd: v.optional(v.string()),
    windGustQcd: v.optional(v.string()),
    altimeterQcd: v.optional(v.string()),
    firstSeenAt: v.number(),
    lastSeenAt: v.number(),
    updatedAt: v.number(),
  }).index("by_station_date_ts", ["stationIcao", "date", "obsTimeUtc"]),

  madisHfmDailySummaries: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    obsCount: v.number(),
    latestObsTimeUtc: v.optional(v.number()),
    latestObsTimeLocal: v.optional(v.string()),
    maxTempC: v.optional(v.number()),
    maxTempF: v.optional(v.number()),
    maxTempAtUtc: v.optional(v.number()),
    maxTempAtLocal: v.optional(v.string()),
    minTempC: v.optional(v.number()),
    minTempF: v.optional(v.number()),
    minTempAtUtc: v.optional(v.number()),
    minTempAtLocal: v.optional(v.string()),
    updatedAt: v.number(),
  }).index("by_station_date", ["stationIcao", "date"]),

  weatherComPwsObservations: defineTable({
    stationIcao: v.string(),
    pwsStationId: v.string(),
    source: v.string(),
    keySource: v.string(),
    date: v.string(),
    obsTimeUtc: v.number(),
    obsTimeLocal: v.string(),
    neighborhood: v.optional(v.string()),
    softwareType: v.optional(v.string()),
    country: v.optional(v.string()),
    latitude: v.optional(v.number()),
    longitude: v.optional(v.number()),
    qcStatus: v.optional(v.number()),
    realtimeFrequency: v.optional(v.number()),
    solarRadiation: v.optional(v.number()),
    uv: v.optional(v.number()),
    relativeHumidity: v.optional(v.number()),
    windDirDegrees: v.optional(v.number()),
    tempC: v.optional(v.number()),
    tempF: v.optional(v.number()),
    dewpointC: v.optional(v.number()),
    dewpointF: v.optional(v.number()),
    heatIndexC: v.optional(v.number()),
    heatIndexF: v.optional(v.number()),
    windChillC: v.optional(v.number()),
    windChillF: v.optional(v.number()),
    windSpeedMph: v.optional(v.number()),
    windSpeedMps: v.optional(v.number()),
    windGustMph: v.optional(v.number()),
    windGustMps: v.optional(v.number()),
    pressureInHg: v.optional(v.number()),
    pressureHpa: v.optional(v.number()),
    precipRateIn: v.optional(v.number()),
    precipTotalIn: v.optional(v.number()),
    elevFt: v.optional(v.number()),
    firstSeenAt: v.number(),
    lastSeenAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_station_pws_date_ts", [
      "stationIcao",
      "pwsStationId",
      "date",
      "obsTimeUtc",
    ])
    .index("by_station_date_ts", ["stationIcao", "date", "obsTimeUtc"]),

  weatherComPwsDailySummaries: defineTable({
    stationIcao: v.string(),
    pwsStationId: v.string(),
    source: v.string(),
    keySource: v.string(),
    date: v.string(),
    obsCount: v.number(),
    latestObsTimeUtc: v.optional(v.number()),
    latestObsTimeLocal: v.optional(v.string()),
    latestTempC: v.optional(v.number()),
    latestTempF: v.optional(v.number()),
    latestQcStatus: v.optional(v.number()),
    latestNeighborhood: v.optional(v.string()),
    maxTempC: v.optional(v.number()),
    maxTempF: v.optional(v.number()),
    maxTempAtUtc: v.optional(v.number()),
    maxTempAtLocal: v.optional(v.string()),
    minTempC: v.optional(v.number()),
    minTempF: v.optional(v.number()),
    minTempAtUtc: v.optional(v.number()),
    minTempAtLocal: v.optional(v.string()),
    updatedAt: v.number(),
  })
    .index("by_station_pws_date", ["stationIcao", "pwsStationId", "date"])
    .index("by_station_date", ["stationIcao", "date"]),

  parisMeteoFranceObservations: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    obsTimeUtc: v.number(),
    obsTimeLocal: v.string(),
    tempC: v.number(),
    tempF: v.number(),
    dewpointC: v.optional(v.number()),
    humidity: v.optional(v.number()),
    windSpeedMps: v.optional(v.number()),
    windDirection: v.optional(v.number()),
    windGustMps: v.optional(v.number()),
    pressureHpa: v.optional(v.number()),
    visibility: v.optional(v.number()),
    source: v.string(),
    createdAt: v.number(),
  }).index("by_station_date_ts", ["stationIcao", "date", "obsTimeUtc"]),

  parisMeteoFranceHourlyForecasts: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    forecastTimeUtc: v.number(),
    forecastTimeLocal: v.string(),
    tempC: v.number(),
    tempF: v.number(),
    humidity: v.optional(v.number()),
    windSpeedMps: v.optional(v.number()),
    windDirection: v.optional(v.number()),
    windGustMps: v.optional(v.number()),
    cloudCover: v.optional(v.number()),
    weatherDescription: v.optional(v.string()),
    rain1h: v.optional(v.number()),
    capturedAt: v.number(),
  }).index("by_station_date_ts", ["stationIcao", "date", "forecastTimeUtc"]),

  aerowebMetarObservations: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    obsTimeUtc: v.number(),
    obsTimeLocal: v.string(),
    reportType: v.union(v.literal("METAR"), v.literal("SPECI")),
    tempC: v.number(),
    tempF: v.number(),
    rawMetar: v.string(),
    source: v.string(),
    aerowebFirstSeenAt: v.optional(v.number()),
    updatedAt: v.number(),
  }).index("by_station_date_ts", ["stationIcao", "date", "obsTimeUtc"]),

  aerowebDailySummaries: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    obsCount: v.number(),
    latestObsTimeUtc: v.optional(v.number()),
    latestObsTimeLocal: v.optional(v.string()),
    latestReportType: v.optional(v.string()),
    latestTempC: v.optional(v.number()),
    latestTempF: v.optional(v.number()),
    latestRawMetar: v.optional(v.string()),
    maxTempC: v.optional(v.number()),
    maxTempF: v.optional(v.number()),
    maxTempAtUtc: v.optional(v.number()),
    maxTempAtLocal: v.optional(v.string()),
    minTempC: v.optional(v.number()),
    minTempF: v.optional(v.number()),
    minTempAtUtc: v.optional(v.number()),
    minTempAtLocal: v.optional(v.string()),
    updatedAt: v.number(),
  }).index("by_station_date", ["stationIcao", "date"]),

  aerowebPublishRaceReports: defineTable({
    stationIcao: v.string(),
    reportDateLocal: v.string(),
    reportTsUtc: v.number(),
    reportType: v.optional(v.union(v.literal("METAR"), v.literal("SPECI"))),
    rawMetar: v.optional(v.string()),
    aerowebRawMetar: v.optional(v.string()),
    tgftpRawMetar: v.optional(v.string()),
    aerowebFirstSeenAt: v.optional(v.number()),
    tgftpFirstSeenAt: v.optional(v.number()),
    tgftpLastModifiedAt: v.optional(v.number()),
    winner: v.optional(
      v.union(v.literal("aeroweb"), v.literal("tgftp"), v.literal("tie")),
    ),
    leadMs: v.optional(v.number()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_station_reportTs", ["stationIcao", "reportTsUtc"]),

  preflightMetarObservations: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    obsTimeUtc: v.number(),
    obsTimeLocal: v.string(),
    reportType: v.union(v.literal("METAR"), v.literal("SPECI")),
    tempC: v.number(),
    tempF: v.number(),
    rawMetar: v.string(),
    source: v.string(),
    preflightFirstSeenAt: v.optional(v.number()),
    updatedAt: v.number(),
  }).index("by_station_date_ts", ["stationIcao", "date", "obsTimeUtc"]),

  preflightDailySummaries: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    obsCount: v.number(),
    latestObsTimeUtc: v.optional(v.number()),
    latestObsTimeLocal: v.optional(v.string()),
    latestReportType: v.optional(v.string()),
    latestTempC: v.optional(v.number()),
    latestTempF: v.optional(v.number()),
    latestRawMetar: v.optional(v.string()),
    maxTempC: v.optional(v.number()),
    maxTempF: v.optional(v.number()),
    maxTempAtUtc: v.optional(v.number()),
    maxTempAtLocal: v.optional(v.string()),
    minTempC: v.optional(v.number()),
    minTempF: v.optional(v.number()),
    minTempAtUtc: v.optional(v.number()),
    minTempAtLocal: v.optional(v.string()),
    updatedAt: v.number(),
  }).index("by_station_date", ["stationIcao", "date"]),

  preflightPublishRaceReports: defineTable({
    stationIcao: v.string(),
    reportDateLocal: v.string(),
    reportTsUtc: v.number(),
    reportType: v.optional(v.union(v.literal("METAR"), v.literal("SPECI"))),
    rawMetar: v.optional(v.string()),
    aerowebRawMetar: v.optional(v.string()),
    preflightRawMetar: v.optional(v.string()),
    tgftpRawMetar: v.optional(v.string()),
    aerowebFirstSeenAt: v.optional(v.number()),
    preflightFirstSeenAt: v.optional(v.number()),
    statusFirstSeenAt: v.optional(v.number()),
    tgftpFirstSeenAt: v.optional(v.number()),
    tgftpLastModifiedAt: v.optional(v.number()),
    winner: v.optional(
      v.union(
        v.literal("aeroweb"),
        v.literal("preflight"),
        v.literal("tgftp"),
        v.literal("tie"),
      ),
    ),
    leadMs: v.optional(v.number()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_station_reportTs", ["stationIcao", "reportTsUtc"]),

  madridMetarObservations: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    obsTimeUtc: v.number(),
    obsTimeLocal: v.string(),
    reportType: v.union(v.literal("METAR"), v.literal("SPECI")),
    tempC: v.number(),
    tempF: v.number(),
    rawMetar: v.string(),
    source: v.string(),
    aemetFirstSeenAt: v.optional(v.number()),
    updatedAt: v.number(),
  }).index("by_station_date_ts", ["stationIcao", "date", "obsTimeUtc"]),

  madridDailySummaries: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    obsCount: v.number(),
    latestObsTimeUtc: v.optional(v.number()),
    latestObsTimeLocal: v.optional(v.string()),
    latestReportType: v.optional(v.string()),
    latestTempC: v.optional(v.number()),
    latestTempF: v.optional(v.number()),
    latestRawMetar: v.optional(v.string()),
    maxTempC: v.optional(v.number()),
    maxTempF: v.optional(v.number()),
    maxTempAtUtc: v.optional(v.number()),
    maxTempAtLocal: v.optional(v.string()),
    minTempC: v.optional(v.number()),
    minTempF: v.optional(v.number()),
    minTempAtUtc: v.optional(v.number()),
    minTempAtLocal: v.optional(v.string()),
    updatedAt: v.number(),
  }).index("by_station_date", ["stationIcao", "date"]),

  madridPublishRaceReports: defineTable({
    stationIcao: v.string(),
    reportDateLocal: v.string(),
    reportTsUtc: v.number(),
    reportType: v.optional(v.union(v.literal("METAR"), v.literal("SPECI"))),
    rawMetar: v.optional(v.string()),
    aemetRawMetar: v.optional(v.string()),
    tgftpRawMetar: v.optional(v.string()),
    aemetFirstSeenAt: v.optional(v.number()),
    tgftpFirstSeenAt: v.optional(v.number()),
    tgftpLastModifiedAt: v.optional(v.number()),
    winner: v.optional(
      v.union(v.literal("aemet"), v.literal("tgftp"), v.literal("tie")),
    ),
    leadMs: v.optional(v.number()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_station_reportTs", ["stationIcao", "reportTsUtc"]),

  madridDatisObservations: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    reportTsUtc: v.number(),
    reportTimeLocal: v.string(),
    reportKind: v.union(v.literal("ARR"), v.literal("DEP")),
    designator: v.string(),
    tempC: v.number(),
    tempF: v.number(),
    dewPointC: v.number(),
    dewPointF: v.number(),
    receivedAtUtc: v.number(),
    receivedAtLocal: v.string(),
    deliveryLagMs: v.number(),
    source: v.string(),
    dedupeKey: v.string(),
    capturedAt: v.number(),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_station_date_report_ts", ["stationIcao", "date", "reportTsUtc"])
    .index("by_station_report_ts", ["stationIcao", "reportTsUtc"])
    .index("by_station_dedupe_key", ["stationIcao", "dedupeKey"]),

  madridDatisCollectorStatus: defineTable({
    stationIcao: v.string(),
    status: v.union(
      v.literal("fetching"),
      v.literal("ok"),
      v.literal("no_data"),
      v.literal("error"),
      v.literal("rate_limited"),
    ),
    configured: v.boolean(),
    mode: v.union(v.literal("manual"), v.literal("scheduled")),
    lastAttemptAt: v.number(),
    lastSuccessAt: v.optional(v.number()),
    latestReportTsUtc: v.optional(v.number()),
    fetchedCount: v.optional(v.number()),
    parsedCount: v.optional(v.number()),
    rejectedCount: v.optional(v.number()),
    duplicateCount: v.optional(v.number()),
    insertedCount: v.optional(v.number()),
    updatedCount: v.optional(v.number()),
    unchangedCount: v.optional(v.number()),
    lastError: v.optional(v.string()),
    retryAfterAt: v.optional(v.number()),
    updatedAt: v.number(),
  }).index("by_station", ["stationIcao"]),

  madridDatisStreamObservations: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    reportTsUtc: v.number(),
    reportTimeLocal: v.string(),
    reportKind: v.union(v.literal("ARR"), v.literal("DEP")),
    designator: v.string(),
    tempC: v.number(),
    tempF: v.number(),
    dewPointC: v.number(),
    dewPointF: v.number(),
    receivedAtUtc: v.number(),
    receivedAtLocal: v.string(),
    deliveryLagMs: v.number(),
    source: v.literal("airframes_acars_datis_stream"),
    dedupeKey: v.string(),
    capturedAt: v.number(),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_station_date_report_ts", ["stationIcao", "date", "reportTsUtc"])
    .index("by_station_report_ts", ["stationIcao", "reportTsUtc"])
    .index("by_station_dedupe_key", ["stationIcao", "dedupeKey"]),

  madridDatisStreamStatus: defineTable({
    stationIcao: v.string(),
    status: v.union(
      v.literal("queued"),
      v.literal("connecting"),
      v.literal("listening"),
      v.literal("backoff"),
    ),
    configured: v.boolean(),
    generation: v.string(),
    leaseUntil: v.number(),
    attemptCount: v.number(),
    consecutiveFailures: v.number(),
    lastAttemptAt: v.number(),
    sessionStartedAt: v.optional(v.number()),
    sessionEndedAt: v.optional(v.number()),
    lastConnectedAt: v.optional(v.number()),
    lastSubscribedAt: v.optional(v.number()),
    lastHeartbeatAt: v.optional(v.number()),
    lastProviderEventAt: v.optional(v.number()),
    lastMatchAt: v.optional(v.number()),
    lastSuccessAt: v.optional(v.number()),
    latestReportTsUtc: v.optional(v.number()),
    retryAfterAt: v.optional(v.number()),
    lastError: v.optional(v.string()),
    sessionProviderEventCount: v.number(),
    sessionCandidateCount: v.number(),
    sessionParsedCount: v.number(),
    sessionStoredCount: v.number(),
    totalProviderEventCount: v.number(),
    totalCandidateCount: v.number(),
    totalParsedCount: v.number(),
    totalStoredCount: v.number(),
    updatedAt: v.number(),
  }).index("by_station", ["stationIcao"]),

  milanMetarObservations: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    obsTimeUtc: v.number(),
    obsTimeLocal: v.string(),
    reportType: v.union(v.literal("METAR"), v.literal("SPECI")),
    tempC: v.number(),
    tempF: v.number(),
    rawMetar: v.string(),
    source: v.string(),
    meteoAmFirstSeenAt: v.optional(v.number()),
    updatedAt: v.number(),
  }).index("by_station_date_ts", ["stationIcao", "date", "obsTimeUtc"]),

  milanDailySummaries: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    obsCount: v.number(),
    latestObsTimeUtc: v.optional(v.number()),
    latestObsTimeLocal: v.optional(v.string()),
    latestReportType: v.optional(v.string()),
    latestTempC: v.optional(v.number()),
    latestTempF: v.optional(v.number()),
    latestRawMetar: v.optional(v.string()),
    maxTempC: v.optional(v.number()),
    maxTempF: v.optional(v.number()),
    maxTempAtUtc: v.optional(v.number()),
    maxTempAtLocal: v.optional(v.string()),
    minTempC: v.optional(v.number()),
    minTempF: v.optional(v.number()),
    minTempAtUtc: v.optional(v.number()),
    minTempAtLocal: v.optional(v.string()),
    updatedAt: v.number(),
  }).index("by_station_date", ["stationIcao", "date"]),

  milanPublishRaceReports: defineTable({
    stationIcao: v.string(),
    reportDateLocal: v.string(),
    reportTsUtc: v.number(),
    reportType: v.optional(v.union(v.literal("METAR"), v.literal("SPECI"))),
    rawMetar: v.optional(v.string()),
    meteoAmRawMetar: v.optional(v.string()),
    tgftpRawMetar: v.optional(v.string()),
    meteoAmFirstSeenAt: v.optional(v.number()),
    tgftpFirstSeenAt: v.optional(v.number()),
    tgftpLastModifiedAt: v.optional(v.number()),
    winner: v.optional(
      v.union(v.literal("meteoam"), v.literal("tgftp"), v.literal("tie")),
    ),
    leadMs: v.optional(v.number()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_station_reportTs", ["stationIcao", "reportTsUtc"]),

  madridAemetHourlyForecasts: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    forecastTimeUtc: v.number(),
    forecastTimeLocal: v.string(),
    tempC: v.number(),
    tempF: v.number(),
    humidity: v.optional(v.number()),
    windSpeedKph: v.optional(v.number()),
    windDirection: v.optional(v.string()),
    skyDescription: v.optional(v.string()),
    precipitation: v.optional(v.number()),
    capturedAt: v.number(),
  }).index("by_station_date_ts", ["stationIcao", "date", "forecastTimeUtc"]),

  madridAemetStationObservations: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    obsTimeUtc: v.number(),
    obsTimeLocal: v.string(),
    tempC: v.number(),
    tempF: v.number(),
    humidity: v.optional(v.number()),
    dewPointC: v.optional(v.number()),
    windSpeedKmh: v.optional(v.number()),
    windDirection: v.optional(v.number()),
    pressureHpa: v.optional(v.number()),
    precipMm: v.optional(v.number()),
    source: v.string(),
    capturedAt: v.number(),
  }).index("by_station_date_ts", ["stationIcao", "date", "obsTimeUtc"]),

  madridSynopObservations: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    obsTimeUtc: v.number(),
    obsTimeLocal: v.string(),
    tempC: v.number(),
    tempF: v.number(),
    dewPointC: v.optional(v.number()),
    rawSynop: v.string(),
    source: v.string(),
    capturedAt: v.number(),
  }).index("by_station_date_ts", ["stationIcao", "date", "obsTimeUtc"]),

  nzwnMetServiceObservations: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    obsTimeUtc: v.number(),
    obsTimeLocal: v.string(),
    tempC: v.number(),
    tempF: v.number(),
    relativeHumidity: v.optional(v.number()),
    windSpeedKph: v.optional(v.number()),
    windGustKph: v.optional(v.number()),
    windDirection: v.optional(v.string()),
    pressureHpa: v.optional(v.number()),
    source: v.string(),
    createdAt: v.number(),
  })
    .index("by_station_date_ts", ["stationIcao", "date", "obsTimeUtc"])
    .index("by_station_source_ts", ["stationIcao", "source", "obsTimeUtc"]),

  nzwnMetServiceCollectorStatus: defineTable({
    stationIcao: v.string(),
    status: v.union(
      v.literal("ok"),
      v.literal("no_data"),
      v.literal("error"),
      v.literal("approval_required"),
      v.literal("outside_collection_window"),
    ),
    configured: v.boolean(),
    lastAttemptAt: v.number(),
    lastAttemptAtLocal: v.string(),
    lastSuccessAt: v.optional(v.number()),
    lastSuccessAtLocal: v.optional(v.string()),
    latestObsTimeUtc: v.optional(v.number()),
    latestObsTimeLocal: v.optional(v.string()),
    lastError: v.optional(v.string()),
    lastIngestResult: v.optional(v.string()),
    updatedAt: v.number(),
  }).index("by_station", ["stationIcao"]),

  nzwnMetServiceHourlyForecasts: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    forecastTimeUtc: v.number(),
    forecastTimeLocal: v.string(),
    tempC: v.number(),
    tempF: v.number(),
    windSpeedKph: v.optional(v.number()),
    windDirection: v.optional(v.string()),
    rainfall: v.optional(v.number()),
    capturedAt: v.number(),
  }).index("by_station_date_ts", ["stationIcao", "date", "forecastTimeUtc"]),

  nzwnForecastPredictions: defineTable({
    stationIcao: v.string(),
    provider: v.literal("metservice"),
    targetDate: v.string(),
    capturedAt: v.number(),
    capturedAtLocal: v.string(),
    captureDate: v.string(),
    leadDays: v.number(),
    minTempC: v.optional(v.number()),
    minTempF: v.optional(v.number()),
    maxTempC: v.optional(v.number()),
    maxTempF: v.optional(v.number()),
    dayPhrase: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_station_provider_target_capturedAt", [
      "stationIcao",
      "provider",
      "targetDate",
      "capturedAt",
    ])
    .index("by_station_captureDate", ["stationIcao", "captureDate"]),

  nzwnDailySummaries: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    obsCount: v.number(),
    maxTempC: v.optional(v.number()),
    maxTempF: v.optional(v.number()),
    maxTempAtUtc: v.optional(v.number()),
    maxTempAtLocal: v.optional(v.string()),
    minTempC: v.optional(v.number()),
    minTempF: v.optional(v.number()),
    minTempAtUtc: v.optional(v.number()),
    minTempAtLocal: v.optional(v.string()),
    latestObsTimeUtc: v.optional(v.number()),
    latestObsTimeLocal: v.optional(v.string()),
    updatedAt: v.number(),
  }).index("by_station_date", ["stationIcao", "date"]),

  ankaraMetarObservations: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    obsTimeUtc: v.number(),
    obsTimeLocal: v.string(),
    reportType: v.union(v.literal("METAR"), v.literal("SPECI")),
    tempC: v.number(),
    tempF: v.number(),
    rawMetar: v.string(),
    source: v.string(),
    mgmFirstSeenAt: v.optional(v.number()),
    updatedAt: v.number(),
  }).index("by_station_date_ts", ["stationIcao", "date", "obsTimeUtc"]),

  ankaraDailySummaries: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    obsCount: v.number(),
    latestObsTimeUtc: v.optional(v.number()),
    latestObsTimeLocal: v.optional(v.string()),
    latestReportType: v.optional(v.string()),
    latestTempC: v.optional(v.number()),
    latestTempF: v.optional(v.number()),
    latestRawMetar: v.optional(v.string()),
    maxTempC: v.optional(v.number()),
    maxTempF: v.optional(v.number()),
    maxTempAtUtc: v.optional(v.number()),
    maxTempAtLocal: v.optional(v.string()),
    minTempC: v.optional(v.number()),
    minTempF: v.optional(v.number()),
    minTempAtUtc: v.optional(v.number()),
    minTempAtLocal: v.optional(v.string()),
    updatedAt: v.number(),
  }).index("by_station_date", ["stationIcao", "date"]),

  ankaraPublishRaceReports: defineTable({
    stationIcao: v.string(),
    reportDateLocal: v.string(),
    reportTsUtc: v.number(),
    reportType: v.optional(v.union(v.literal("METAR"), v.literal("SPECI"))),
    rawMetar: v.optional(v.string()),
    mgmRawMetar: v.optional(v.string()),
    tgftpRawMetar: v.optional(v.string()),
    mgmFirstSeenAt: v.optional(v.number()),
    tgftpFirstSeenAt: v.optional(v.number()),
    tgftpLastModifiedAt: v.optional(v.number()),
    winner: v.optional(
      v.union(v.literal("mgm"), v.literal("tgftp"), v.literal("tie")),
    ),
    leadMs: v.optional(v.number()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_station_reportTs", ["stationIcao", "reportTsUtc"]),

  ankaraMgmObservations: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    obsTimeUtc: v.number(),
    obsTimeLocal: v.string(),
    tempC: v.number(),
    tempF: v.number(),
    humidity: v.optional(v.number()),
    windSpeedMps: v.optional(v.number()),
    windDirection: v.optional(v.number()),
    visibility: v.optional(v.number()),
    pressureHpa: v.optional(v.number()),
    cloudCover: v.optional(v.number()),
    source: v.string(),
    createdAt: v.number(),
  }).index("by_station_date_ts", ["stationIcao", "date", "obsTimeUtc"]),

  ankaraMgmHourlyForecasts: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    forecastTimeUtc: v.number(),
    forecastTimeLocal: v.string(),
    tempC: v.number(),
    tempF: v.number(),
    humidity: v.optional(v.number()),
    windSpeedKph: v.optional(v.number()),
    windDirection: v.optional(v.number()),
    weatherCode: v.optional(v.string()),
    capturedAt: v.number(),
  }).index("by_station_date_ts", ["stationIcao", "date", "forecastTimeUtc"]),

  seoulMetarObservations: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    obsTimeUtc: v.number(),
    obsTimeLocal: v.string(),
    reportType: v.union(v.literal("METAR"), v.literal("SPECI")),
    tempC: v.number(),
    tempF: v.number(),
    rawMetar: v.string(),
    source: v.string(),
    amoFirstSeenAt: v.optional(v.number()),
    updatedAt: v.number(),
  }).index("by_station_date_ts", ["stationIcao", "date", "obsTimeUtc"]),

  seoulDailySummaries: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    obsCount: v.number(),
    latestObsTimeUtc: v.optional(v.number()),
    latestObsTimeLocal: v.optional(v.string()),
    latestReportType: v.optional(v.string()),
    latestTempC: v.optional(v.number()),
    latestTempF: v.optional(v.number()),
    latestRawMetar: v.optional(v.string()),
    maxTempC: v.optional(v.number()),
    maxTempF: v.optional(v.number()),
    maxTempAtUtc: v.optional(v.number()),
    maxTempAtLocal: v.optional(v.string()),
    minTempC: v.optional(v.number()),
    minTempF: v.optional(v.number()),
    minTempAtUtc: v.optional(v.number()),
    minTempAtLocal: v.optional(v.string()),
    updatedAt: v.number(),
  }).index("by_station_date", ["stationIcao", "date"]),

  seoulAmosObservations: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    obsTimeUtc: v.number(),
    obsTimeLocal: v.string(),
    collectionCadence: v.optional(
      v.union(v.literal("one_minute"), v.literal("five_minute")),
    ),
    rwyNo: v.string(),
    rwyDir: v.string(),
    rwyUse: v.optional(v.string()),
    rwyMain: v.optional(v.string()),
    tempC: v.optional(v.number()),
    tempF: v.optional(v.number()),
    dewpointC: v.optional(v.number()),
    dewpointF: v.optional(v.number()),
    qnhHpa: v.optional(v.number()),
    qnhInHg: v.optional(v.number()),
    windDirAvg: v.optional(v.number()),
    windDirMin: v.optional(v.number()),
    windDirMax: v.optional(v.number()),
    windSpeedAvg: v.optional(v.number()),
    windSpeedMin: v.optional(v.number()),
    windSpeedMax: v.optional(v.number()),
    crosswind: v.optional(v.string()),
    headtail: v.optional(v.string()),
    morMeters: v.optional(v.number()),
    rvrMeters: v.optional(v.string()),
    precipMm: v.optional(v.number()),
    source: v.string(),
    rawJson: v.optional(v.string()),
    firstSeenAt: v.optional(v.number()),
    updatedAt: v.number(),
  })
    .index("by_station_date_ts_rwy", [
      "stationIcao",
      "date",
      "obsTimeUtc",
      "rwyNo",
      "rwyDir",
    ])
    .index("by_station_date_ts_rwy_cadence", [
      "stationIcao",
      "date",
      "obsTimeUtc",
      "rwyNo",
      "rwyDir",
      "collectionCadence",
    ])
    .index("by_station_date_rwy_ts", [
      "stationIcao",
      "date",
      "rwyNo",
      "rwyDir",
      "obsTimeUtc",
    ]),

  seoulGk2aSolarObservations: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    obsTimeUtc: v.number(),
    obsTimeLocal: v.string(),
    pointKind: seoulGk2aPointKind,
    sampleKey: v.string(),
    latitude: v.number(),
    longitude: v.number(),
    sourceLatitude: v.optional(v.number()),
    sourceLongitude: v.optional(v.number()),
    upwindMinutes: v.optional(v.number()),
    distanceUpwindKm: v.optional(v.number()),
    dsrWm2: v.optional(v.number()),
    asrWm2: v.optional(v.number()),
    clearSkyDsrWm2: v.number(),
    solarElevationDeg: v.number(),
    transmissionPct: v.optional(v.number()),
    dsrRawLine: v.optional(v.string()),
    asrRawLine: v.optional(v.string()),
    windObservedAtUtc: v.optional(v.number()),
    windDirectionFromDeg: v.optional(v.number()),
    windSpeedKt: v.optional(v.number()),
    windSpeedMps: v.optional(v.number()),
    source: v.string(),
    sourceEndpoint: v.string(),
    sourceFileName: v.optional(v.string()),
    sourceGridRow: v.optional(v.number()),
    sourceGridColumn: v.optional(v.number()),
    dsrQualityFlag: v.optional(v.number()),
    asrQualityFlag: v.optional(v.number()),
    shortwaveQualityFlag: v.optional(v.number()),
    productCadenceMinutes: v.number(),
    collectionRunAt: v.number(),
    firstSeenAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_station_date_sample_ts", [
      "stationIcao",
      "date",
      "sampleKey",
      "obsTimeUtc",
    ])
    .index("by_station_date_point_ts", [
      "stationIcao",
      "date",
      "pointKind",
      "obsTimeUtc",
    ])
    .index("by_station_point_ts", ["stationIcao", "pointKind", "obsTimeUtc"])
    .index("by_station_obs_ts", ["stationIcao", "obsTimeUtc"]),

  seoulGk2aCollectorStatus: defineTable({
    stationIcao: v.string(),
    status: seoulGk2aCollectorStatus,
    configured: v.boolean(),
    lastAttemptAt: v.number(),
    lastAttemptAtLocal: v.string(),
    lastSuccessAt: v.optional(v.number()),
    lastSuccessAtLocal: v.optional(v.string()),
    latestObsTimeUtc: v.optional(v.number()),
    latestObsTimeLocal: v.optional(v.string()),
    lastResolvedFrameTimeUtc: v.optional(v.number()),
    lastError: v.optional(v.string()),
    requestedPointCount: v.optional(v.number()),
    storedRowCount: v.optional(v.number()),
    upwindStatus: v.optional(v.string()),
    windObservedAtUtc: v.optional(v.number()),
    windDirectionFromDeg: v.optional(v.number()),
    windSpeedKt: v.optional(v.number()),
    collectionQueuedAt: v.optional(v.number()),
    collectionInFlightSince: v.optional(v.number()),
    collectionMode: v.optional(v.string()),
    collectionRunId: v.optional(v.string()),
    updatedAt: v.number(),
  }).index("by_station", ["stationIcao"]),

  seoulKmaForecastCollectorStatus: defineTable({
    stationIcao: v.string(),
    status: seoulKmaForecastCollectorStatus,
    collectionQueuedAt: v.number(),
    collectionInFlightSince: v.optional(v.number()),
    collectionMode: v.optional(
      v.union(v.literal("manual"), v.literal("scheduled")),
    ),
    collectionRunId: v.optional(v.string()),
    lastCompletedAt: v.optional(v.number()),
    lastSuccessAt: v.optional(v.number()),
    lastError: v.optional(v.string()),
    dailyRowCount: v.optional(v.number()),
    hourlyRowCount: v.optional(v.number()),
    updatedAt: v.number(),
  }).index("by_station", ["stationIcao"]),

  seoulKmaForecastCaptures: defineTable({
    stationIcao: v.string(),
    stationName: v.string(),
    source: v.literal("kma_amo_airport"),
    sourceUrl: v.string(),
    collectionTrigger: v.union(v.literal("manual"), v.literal("scheduled")),
    capturedAt: v.number(),
    capturedAtLocal: v.string(),
    captureDate: v.string(),
    status: seoulKmaForecastCaptureStatus,
    approvalFlagName: v.string(),
    error: v.optional(v.string()),
    httpStatus: v.optional(v.number()),
    contentType: v.optional(v.string()),
    responseBytes: v.optional(v.number()),
    etag: v.optional(v.string()),
    lastModified: v.optional(v.string()),
    // This timestamp is displayed with the airport's current-condition
    // header. It is not claimed to be a forecast issuance timestamp.
    pageReportedAt: v.optional(v.number()),
    pageReportedAtLocal: v.optional(v.string()),
    dailyRows: v.array(
      v.object({
        date: v.string(),
        forecastType: v.union(v.literal("short_term"), v.literal("midterm")),
        minTempC: v.optional(v.number()),
        minTempF: v.optional(v.number()),
        maxTempC: v.optional(v.number()),
        maxTempF: v.optional(v.number()),
        phrase: v.optional(v.string()),
      }),
    ),
    hourlyRows: v.array(
      v.object({
        date: v.string(),
        forecastTimeUtc: v.number(),
        forecastTimeLocal: v.string(),
        tempC: v.number(),
        tempF: v.number(),
        phrase: v.optional(v.string()),
        conditionCode: v.optional(v.string()),
        ceilingFt: v.optional(v.number()),
        ceilingText: v.optional(v.string()),
        windDirectionDeg: v.optional(v.number()),
        windSpeedKt: v.optional(v.number()),
        windGustKt: v.optional(v.number()),
        windSpeedText: v.optional(v.string()),
        visibilityM: v.optional(v.number()),
        visibilityText: v.optional(v.string()),
        crosswindText: v.optional(v.string()),
      }),
    ),
    createdAt: v.number(),
  })
    .index("by_station_capturedAt", ["stationIcao", "capturedAt"])
    .index("by_station_status_capturedAt", [
      "stationIcao",
      "status",
      "capturedAt",
    ]),

  seoulForecastCaptures: defineTable({
    stationIcao: v.string(),
    stationName: v.string(),
    capturedAt: v.number(),
    capturedAtLocal: v.string(),
    captureDate: v.string(),
    status: seoulForecastStatus,
    weathercomStatus: seoulProviderStatus,
    weathercomError: v.optional(v.string()),
    weathercomForecastDays: v.array(
      v.object({
        date: v.string(),
        minTempC: v.optional(v.number()),
        minTempF: v.optional(v.number()),
        maxTempC: v.optional(v.number()),
        maxTempF: v.optional(v.number()),
        dayPhrase: v.optional(v.string()),
        nightPhrase: v.optional(v.string()),
      }),
    ),
    weathercomHourlyStatus: v.optional(seoulProviderStatus),
    weathercomHourlyError: v.optional(v.string()),
    weathercomHourlyCapturedAt: v.optional(v.number()),
    weathercomHourlyCapturedAtLocal: v.optional(v.string()),
    weathercomHourlyCaptureDate: v.optional(v.string()),
    weathercomHourlyRows: v.optional(v.array(seoulHourlyForecastRow)),
    // Legacy fields remain optional so existing captures continue to validate.
    // Weather.com captures are retained as explicitly secondary guidance.
    googleStatus: v.optional(seoulProviderStatus),
    googleError: v.optional(v.string()),
    googleHourlyRows: v.optional(v.array(seoulHourlyForecastRow)),
    openMeteoStatus: v.optional(seoulProviderStatus),
    openMeteoError: v.optional(v.string()),
    openMeteoHourlyRows: v.optional(v.array(seoulHourlyForecastRow)),
    createdAt: v.number(),
  }).index("by_station_capturedAt", ["stationIcao", "capturedAt"]),

  seoulHourlyForecastPredictions: defineTable({
    stationIcao: v.string(),
    provider: v.literal("weathercom"),
    targetDate: v.string(),
    forecastTimeUtc: v.number(),
    forecastTimeLocal: v.string(),
    capturedAt: v.number(),
    capturedAtLocal: v.string(),
    captureDate: v.string(),
    tempC: v.number(),
    tempF: v.number(),
    phrase: v.optional(v.string()),
    cloudCoverPct: v.optional(v.number()),
    forecastCaptureId: v.id("seoulForecastCaptures"),
    createdAt: v.number(),
  })
    .index("by_station_provider_target_capturedAt", [
      "stationIcao",
      "provider",
      "targetDate",
      "capturedAt",
    ])
    .index("by_station_provider_valid_capturedAt", [
      "stationIcao",
      "provider",
      "forecastTimeUtc",
      "capturedAt",
    ])
    .index("by_forecast_capture_id", ["forecastCaptureId"]),

  seoulAmosDailySummaries: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    rwyNo: v.literal("2"),
    rwyDir: v.literal("15L"),
    obsCount: v.number(),
    oneMinuteObsCount: v.number(),
    fallbackObsCount: v.number(),
    firstObsTimeUtc: v.optional(v.number()),
    firstObsTimeLocal: v.optional(v.string()),
    latestObsTimeUtc: v.optional(v.number()),
    latestObsTimeLocal: v.optional(v.string()),
    latestTempC: v.optional(v.number()),
    latestTempF: v.optional(v.number()),
    maxTempC: v.optional(v.number()),
    maxTempF: v.optional(v.number()),
    maxTempAtUtc: v.optional(v.number()),
    maxTempAtLocal: v.optional(v.string()),
    minTempC: v.optional(v.number()),
    minTempF: v.optional(v.number()),
    minTempAtUtc: v.optional(v.number()),
    minTempAtLocal: v.optional(v.string()),
    updatedAt: v.number(),
  }).index("by_station_date", ["stationIcao", "date"]),

  seoulHighPredictions: defineTable({
    stationIcao: v.string(),
    targetDate: v.string(),
    revision: v.number(),
    evaluationSlotUtc: v.number(),
    modelVersion: v.string(),
    generatedAt: v.number(),
    generatedAtLocal: v.string(),
    forecastCaptureId: v.optional(
      v.union(v.id("seoulForecastCaptures"), v.id("seoulKmaForecastCaptures")),
    ),
    forecastCapturedAt: v.optional(v.number()),
    forecastAgeMinutes: v.optional(v.number()),
    previousPredictionId: v.optional(v.id("seoulHighPredictions")),
    observedCount: v.number(),
    observedCurrentC: v.optional(v.number()),
    observedCurrentF: v.optional(v.number()),
    observedCurrentAtUtc: v.optional(v.number()),
    observedCurrentAtLocal: v.optional(v.string()),
    observationAgeMinutes: v.optional(v.number()),
    observedHighC: v.optional(v.number()),
    observedHighF: v.optional(v.number()),
    observedHighAtUtc: v.optional(v.number()),
    observedHighAtLocal: v.optional(v.string()),
    slope15mCPerHour: v.optional(v.number()),
    slope30mCPerHour: v.optional(v.number()),
    slope60mCPerHour: v.optional(v.number()),
    currentSmoothedC: v.optional(v.number()),
    lastNearHighAtUtc: v.optional(v.number()),
    lastNearHighAtLocal: v.optional(v.string()),
    minutesSinceNearHigh: v.optional(v.number()),
    dropFromHighC: v.optional(v.number()),
    robustSlope15mCPerHour: v.optional(v.number()),
    robustSlope30mCPerHour: v.optional(v.number()),
    robustSlope60mCPerHour: v.optional(v.number()),
    trend15mCoverageMinutes: v.optional(v.number()),
    trend30mCoverageMinutes: v.optional(v.number()),
    trend60mCoverageMinutes: v.optional(v.number()),
    trendLatestGapMinutes: v.optional(v.number()),
    trailingHourObservationCount: v.optional(v.number()),
    expectedCurrentC: v.optional(v.number()),
    liveBiasC: v.optional(v.number()),
    kmaLiveBiasC: v.optional(v.number()),
    kmaRemainingBestHighC: v.optional(v.number()),
    kmaRemainingUpperC: v.optional(v.number()),
    kmaHourlyPointCount: v.optional(v.number()),
    kmaFutureHourlyPointCount: v.optional(v.number()),
    kmaHourlyCoverageEndUtc: v.optional(v.number()),
    kmaMaxHourlyGapMinutes: v.optional(v.number()),
    kmaDailyHourlyHighGapC: v.optional(v.number()),
    kmaRevisionUpwardDetected: v.optional(v.boolean()),
    nowcastUpperC: v.optional(v.number()),
    remainingRuleCeilingC: v.optional(v.number()),
    predictedHighC: v.number(),
    predictedHighF: v.number(),
    confidenceLowC: v.optional(v.number()),
    confidenceLowF: v.optional(v.number()),
    confidenceHighC: v.optional(v.number()),
    confidenceHighF: v.optional(v.number()),
    peakWindowStartUtc: v.optional(v.number()),
    peakWindowEndUtc: v.optional(v.number()),
    peakWindowStartLocal: v.optional(v.string()),
    peakWindowEndLocal: v.optional(v.string()),
    firstKmaPeakTimeUtc: v.optional(v.number()),
    firstKmaPeakTimeLocal: v.optional(v.string()),
    lastKmaPeakTimeUtc: v.optional(v.number()),
    lastKmaPeakTimeLocal: v.optional(v.string()),
    kmaPeakWindowEndUtc: v.optional(v.number()),
    kmaPeakWindowEndLocal: v.optional(v.string()),
    targetC: v.optional(v.number()),
    marginBelowTargetC: v.optional(v.number()),
    decisionStatus: v.optional(seoulPeakDecisionStatus),
    candidateSinceUtc: v.optional(v.number()),
    candidateSinceLocal: v.optional(v.string()),
    consecutivePasses: v.optional(v.number()),
    blockerCodes: v.optional(v.array(v.string())),
    blockerDescriptions: v.optional(v.array(v.string())),
    solarStatus: v.optional(v.string()),
    solarUsefulEnergyRemaining: v.optional(v.boolean()),
    solarDecisionRequired: v.optional(v.boolean()),
    solarObservedAtUtc: v.optional(v.number()),
    solarObservedAtLocal: v.optional(v.string()),
    solarObservationAgeMinutes: v.optional(v.number()),
    solarDsrWm2: v.optional(v.number()),
    solarAsrWm2: v.optional(v.number()),
    solarClearSkyDsrWm2: v.optional(v.number()),
    solarDsrChange30mWm2: v.optional(v.number()),
    solarClearSkyDsrChange30mWm2: v.optional(v.number()),
    solarTransmissionPct: v.optional(v.number()),
    solarTransmissionTrend: v.optional(seoulSolarTrendStatus),
    solarTransmissionSlopePctPointsPerHour: v.optional(v.number()),
    solarUpwindSignal: v.optional(seoulSolarUpwindSignal),
    solarUpwindEtaMinutes: v.optional(v.number()),
    solarUpwindTransmissionPct: v.optional(v.number()),
    solarUpwindDifferencePctPoints: v.optional(v.number()),
    solarUpwindPointCount: v.optional(v.number()),
    solarWindObservedAtUtc: v.optional(v.number()),
    solarWindDirectionFromDeg: v.optional(v.number()),
    solarWindSpeedKt: v.optional(v.number()),
    solarLatitude: v.optional(v.number()),
    solarLongitude: v.optional(v.number()),
    solarSourceLatitude: v.optional(v.number()),
    solarSourceLongitude: v.optional(v.number()),
    solarSource: v.optional(v.string()),
    solarSourceEndpoint: v.optional(v.string()),
    solarSourceFileName: v.optional(v.string()),
    solarSourceGridRow: v.optional(v.number()),
    solarSourceGridColumn: v.optional(v.number()),
    solarSampleKey: v.optional(v.string()),
    solarProductCadenceMinutes: v.optional(v.number()),
    solarCollectionRunAt: v.optional(v.number()),
    solarDsrQualityFlag: v.optional(v.number()),
    solarAsrQualityFlag: v.optional(v.number()),
    solarShortwaveQualityFlag: v.optional(v.number()),
    secondary16LObservedAtUtc: v.optional(v.number()),
    secondary16LObservedAtLocal: v.optional(v.string()),
    secondary16LObservationAgeMinutes: v.optional(v.number()),
    secondary16LCurrentC: v.optional(v.number()),
    secondary16LCurrentF: v.optional(v.number()),
    secondary16LSlope15mCPerHour: v.optional(v.number()),
    secondary16LSlope30mCPerHour: v.optional(v.number()),
    secondary16LDifferenceFrom15LC: v.optional(v.number()),
    secondary16LDifferenceChange30mC: v.optional(v.number()),
    windObservedAtUtc: v.optional(v.number()),
    windDirectionDeg: v.optional(v.number()),
    windSpeedKt: v.optional(v.number()),
    windDirectionChange30mDeg: v.optional(v.number()),
    windSpeedChange30mKt: v.optional(v.number()),
    forecastWindDirectionChange2hDeg: v.optional(v.number()),
    forecastWindSpeedChange2hKt: v.optional(v.number()),
    materialWindShiftDetected: v.optional(v.boolean()),
    currentDewpointC: v.optional(v.number()),
    dewpointChange30mC: v.optional(v.number()),
    dewpointRisingWithWindShift: v.optional(v.boolean()),
    currentPrecipMm: v.optional(v.number()),
    precipObservedInLast60m: v.optional(v.boolean()),
    recentPrecipEndedAtUtc: v.optional(v.number()),
    rainEndedClearingRisk: v.optional(v.boolean()),
    weathercomRemainingHighC: v.optional(v.number()),
    weathercomForecastCapturedAt: v.optional(v.number()),
    weathercomForecastAgeMinutes: v.optional(v.number()),
    weathercomVetoActive: v.optional(v.boolean()),
    status: seoulPredictionStatus,
    reason: v.string(),
    providerDetails: v.array(seoulProviderDetail),
    hourlyEnsembleCurve: v.array(
      v.object({
        forecastTimeUtc: v.number(),
        forecastTimeLocal: v.string(),
        tempC: v.number(),
        tempF: v.number(),
        providerCount: v.number(),
        cloudCoverPct: v.optional(v.number()),
        cloudProviderCount: v.optional(v.number()),
        phrase: v.optional(v.string()),
        conditionCode: v.optional(v.string()),
        ceilingFt: v.optional(v.number()),
        ceilingText: v.optional(v.string()),
        windDirectionDeg: v.optional(v.number()),
        windSpeedKt: v.optional(v.number()),
        windGustKt: v.optional(v.number()),
        windSpeedText: v.optional(v.string()),
        visibilityM: v.optional(v.number()),
        visibilityText: v.optional(v.string()),
        crosswindText: v.optional(v.string()),
      }),
    ),
    createdAt: v.number(),
  })
    .index("by_station_date_revision", [
      "stationIcao",
      "targetDate",
      "revision",
    ])
    .index("by_station_date_model_revision", [
      "stationIcao",
      "targetDate",
      "modelVersion",
      "revision",
    ])
    .index("by_station_date_model_target_revision", [
      "stationIcao",
      "targetDate",
      "modelVersion",
      "targetC",
      "revision",
    ])
    .index("by_station_date_generatedAt", [
      "stationIcao",
      "targetDate",
      "generatedAt",
    ])
    .index("by_station_date_slot", [
      "stationIcao",
      "targetDate",
      "evaluationSlotUtc",
    ]),

  seoulPeakDecisionState: defineTable({
    stationIcao: v.string(),
    targetDate: v.string(),
    modelVersion: v.string(),
    targetC: v.number(),
    candidateSinceUtc: v.optional(v.number()),
    consecutivePasses: v.number(),
    lastEvaluationAt: v.number(),
    lastEvaluationSlotUtc: v.number(),
    lastRuleCeilingC: v.optional(v.number()),
    lastCurrentSmoothedC: v.optional(v.number()),
    lastKmaForecastCaptureId: v.optional(v.id("seoulKmaForecastCaptures")),
    lastKmaDailyHighC: v.optional(v.number()),
    lastKmaRemainingUpperC: v.optional(v.number()),
    lastKmaHourlyRows: v.optional(
      v.array(
        v.object({
          forecastTimeUtc: v.number(),
          tempC: v.number(),
        }),
      ),
    ),
    solarDecisionRequired: v.optional(v.boolean()),
    currentState: seoulPeakDecisionStatus,
    blockerCodes: v.array(v.string()),
    blockerDescriptions: v.array(v.string()),
    lastPredictionId: v.optional(v.id("seoulHighPredictions")),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_station_date_model_target", [
    "stationIcao",
    "targetDate",
    "modelVersion",
    "targetC",
  ]),

  seoulPeakActiveTargets: defineTable({
    stationIcao: v.string(),
    targetDate: v.string(),
    modelVersion: v.string(),
    targetC: v.number(),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_station_date_model_target", [
    "stationIcao",
    "targetDate",
    "modelVersion",
    "targetC",
  ]),

  seoulHighEvaluations: defineTable({
    stationIcao: v.string(),
    targetDate: v.string(),
    // Optional so evaluations written by older forecast models continue to
    // validate. Current readers select the exact active model version.
    modelVersion: v.optional(v.string()),
    finalizedAt: v.number(),
    finalizedAtLocal: v.string(),
    actualHighC: v.number(),
    actualHighF: v.number(),
    actualHighAtUtc: v.number(),
    actualHighAtLocal: v.string(),
    obsCount: v.number(),
    initialPredictionId: v.optional(v.id("seoulHighPredictions")),
    initialPredictedHighC: v.optional(v.number()),
    initialPredictedHighF: v.optional(v.number()),
    initialErrorC: v.optional(v.number()),
    initialAbsoluteErrorC: v.optional(v.number()),
    finalPredictionId: v.optional(v.id("seoulHighPredictions")),
    finalPredictedHighC: v.optional(v.number()),
    finalPredictedHighF: v.optional(v.number()),
    finalErrorC: v.optional(v.number()),
    finalAbsoluteErrorC: v.optional(v.number()),
    finalPeakWindowStartUtc: v.optional(v.number()),
    finalPeakWindowEndUtc: v.optional(v.number()),
    peakWindowHit: v.optional(v.boolean()),
    thresholdTargetC: v.optional(v.number()),
    firstUnlikelyPredictionId: v.optional(v.id("seoulHighPredictions")),
    firstUnlikelyAtUtc: v.optional(v.number()),
    firstUnlikelyAtLocal: v.optional(v.string()),
    firstUnlikelyRuleCeilingC: v.optional(v.number()),
    firstUnlikelyFutureHighC: v.optional(v.number()),
    firstUnlikelyMarginBelowTargetC: v.optional(v.number()),
    firstUnlikelyWasFalse: v.optional(v.boolean()),
    targetReachedAfterFirstUnlikely: v.optional(v.boolean()),
    targetReachedAfterFirstUnlikelyAtUtc: v.optional(v.number()),
    unlikelyDeclarationCount: v.optional(v.number()),
    evaluatedUnlikelyDeclarationCount: v.optional(v.number()),
    censoredUnlikelyDeclarationCount: v.optional(v.number()),
    unlikelyRevocationCount: v.optional(v.number()),
    falseUnlikelyDeclarationCount: v.optional(v.number()),
    thresholdObservationCoverageComplete: v.optional(v.boolean()),
    thresholdObservationCoverageEndUtc: v.optional(v.number()),
    thresholdMaxFutureGapMinutes: v.optional(v.number()),
    firstCorrectUnlikelyAtUtc: v.optional(v.number()),
    firstCorrectUnlikelyAtLocal: v.optional(v.string()),
    checkpoints: v.optional(
      v.array(
        v.object({
          localHour: v.number(),
          cutoffAtUtc: v.number(),
          cutoffAtLocal: v.string(),
          predictionId: v.optional(v.id("seoulHighPredictions")),
          predictedHighC: v.optional(v.number()),
          predictedHighF: v.optional(v.number()),
          errorC: v.optional(v.number()),
          absoluteErrorC: v.optional(v.number()),
          peakWindowStartUtc: v.optional(v.number()),
          peakWindowEndUtc: v.optional(v.number()),
          peakWindowHit: v.optional(v.boolean()),
        }),
      ),
    ),
    revisionCount: v.number(),
    createdAt: v.number(),
  })
    .index("by_station_date", ["stationIcao", "targetDate"])
    .index("by_station_finalizedAt", ["stationIcao", "finalizedAt"])
    .index("by_station_model_date", [
      "stationIcao",
      "modelVersion",
      "targetDate",
    ])
    .index("by_station_model_date_target", [
      "stationIcao",
      "modelVersion",
      "targetDate",
      "thresholdTargetC",
    ])
    .index("by_station_model_finalizedAt", [
      "stationIcao",
      "modelVersion",
      "finalizedAt",
    ])
    .index("by_station_model_target_finalizedAt", [
      "stationIcao",
      "modelVersion",
      "thresholdTargetC",
      "finalizedAt",
    ]),

  seoulPublishRaceReports: defineTable({
    stationIcao: v.string(),
    reportDateLocal: v.string(),
    reportTsUtc: v.number(),
    reportType: v.optional(v.union(v.literal("METAR"), v.literal("SPECI"))),
    rawMetar: v.optional(v.string()),
    amoRawMetar: v.optional(v.string()),
    tgftpRawMetar: v.optional(v.string()),
    amoFirstSeenAt: v.optional(v.number()),
    tgftpFirstSeenAt: v.optional(v.number()),
    tgftpLastModifiedAt: v.optional(v.number()),
    winner: v.optional(
      v.union(v.literal("amo"), v.literal("tgftp"), v.literal("tie")),
    ),
    leadMs: v.optional(v.number()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_station_reportTs", ["stationIcao", "reportTsUtc"]),

  mexicoCollectorStatus: defineTable({
    stationIcao: v.string(),
    source: v.string(),
    status: v.union(
      v.literal("idle"),
      v.literal("fetching"),
      v.literal("ok"),
      v.literal("not_modified"),
      v.literal("approval_required"),
      v.literal("error"),
    ),
    lastAttemptAt: v.number(),
    lastSuccessAt: v.optional(v.number()),
    lastError: v.optional(v.string()),
    // Ring buffer of the most recent error finishes (newest last, capped at
    // 20) so multi-minute outages can be diagnosed after the fact; the
    // single lastError field only ever kept the latest message.
    recentErrors: v.optional(
      v.array(v.object({ at: v.number(), message: v.string() })),
    ),
    httpStatus: v.optional(v.number()),
    responseBytes: v.optional(v.number()),
    etag: v.optional(v.string()),
    lastModified: v.optional(v.string()),
    cacheControl: v.optional(v.string()),
    rowCount: v.optional(v.number()),
    updatedAt: v.number(),
  }).index("by_station_source", ["stationIcao", "source"]),

  mexicoMetarObservations: defineTable({
    stationIcao: v.string(),
    reportKey: v.string(),
    rawHash: v.string(),
    date: v.string(),
    obsTimeUtc: v.number(),
    obsTimeLocal: v.string(),
    reportTimeUtc: v.optional(v.number()),
    reportType: v.union(v.literal("METAR"), v.literal("SPECI")),
    isCorrection: v.boolean(),
    tempC: v.optional(v.number()),
    tempF: v.optional(v.number()),
    dewpointC: v.optional(v.number()),
    dewpointF: v.optional(v.number()),
    weather: v.optional(v.string()),
    cloudCover: v.optional(v.string()),
    cloudSummary: v.optional(v.string()),
    flightCategory: v.optional(v.string()),
    windDirectionDeg: v.optional(v.number()),
    windSpeedKt: v.optional(v.number()),
    visibilitySm: v.optional(v.number()),
    rawMetar: v.string(),
    rawProviderJson: v.string(),
    initialAwcReceiptTimeUtc: v.optional(v.number()),
    latestAwcReceiptTimeUtc: v.optional(v.number()),
    firstAwcFetchStartedAt: v.optional(v.number()),
    firstAwcSeenAt: v.optional(v.number()),
    typelessHash: v.optional(v.string()),
    firstSource: v.optional(v.string()),
    relayFirstSeenAt: v.optional(v.number()),
    relaySource: v.optional(v.string()),
    firstSeenAt: v.number(),
    fetchStartedAt: v.number(),
    fetchCompletedAt: v.number(),
    lastSeenAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_station_report_key", ["stationIcao", "reportKey"])
    .index("by_station_date_obs", ["stationIcao", "date", "obsTimeUtc"])
    .index("by_station_obs_hash", ["stationIcao", "obsTimeUtc", "rawHash"])
    .index("by_station_obs_typeless_hash", [
      "stationIcao",
      "obsTimeUtc",
      "typelessHash",
    ]),

  // Earliest application-level sightings of an official MMMX report on relays
  // that cannot always classify report type (NOAA single-station text file).
  // Used only to adopt an earlier firstSeenAt when the canonical row arrives;
  // never rendered as an observation series.
  mexicoRelaySightings: defineTable({
    stationIcao: v.string(),
    source: v.string(),
    date: v.optional(v.string()),
    obsTimeUtc: v.number(),
    typelessHash: v.string(),
    rawReport: v.string(),
    reportTypeHint: v.optional(v.union(v.literal("METAR"), v.literal("SPECI"))),
    isCorrectionHint: v.optional(v.boolean()),
    fileStampUtc: v.optional(v.number()),
    raceSlotUtc: v.optional(v.number()),
    firstSeenAt: v.number(),
    fetchStartedAt: v.number(),
    fetchCompletedAt: v.number(),
    lastSeenAt: v.optional(v.number()),
    adopted: v.boolean(),
    updatedAt: v.number(),
  })
    .index("by_station_source_obs_hash", [
      "stationIcao",
      "source",
      "obsTimeUtc",
      "typelessHash",
    ])
    .index("by_station_obs_hash", ["stationIcao", "obsTimeUtc", "typelessHash"])
    .index("by_station_date", ["stationIcao", "date", "firstSeenAt"]),

  // One row per scheduled paired CAPMA/NOAA attempt. A relay win is counted
  // only when both requests succeeded in the earlier source's polling slot.
  mexicoRelayRaceAttempts: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    raceSlotUtc: v.number(),
    startedAt: v.number(),
    completedAt: v.number(),
    capmaStatus: v.string(),
    noaaStatus: v.string(),
    capmaFetchStartedAt: v.optional(v.number()),
    capmaFetchCompletedAt: v.optional(v.number()),
    noaaFetchStartedAt: v.optional(v.number()),
    noaaFetchCompletedAt: v.optional(v.number()),
    capmaRowCount: v.optional(v.number()),
    noaaRowCount: v.optional(v.number()),
    updatedAt: v.number(),
  })
    .index("by_station_slot", ["stationIcao", "raceSlotUtc"])
    .index("by_station_date_slot", ["stationIcao", "date", "raceSlotUtc"]),

  mexicoTafForecasts: defineTable({
    stationIcao: v.string(),
    tafKey: v.string(),
    rawHash: v.string(),
    rawTaf: v.string(),
    rawProviderJson: v.string(),
    issueTimeUtc: v.number(),
    bulletinTimeUtc: v.optional(v.number()),
    awcDatabaseTimeUtc: v.optional(v.number()),
    validFromUtc: v.number(),
    validToUtc: v.number(),
    isCorrection: v.boolean(),
    isAmendment: v.boolean(),
    temperatureGroups: v.array(
      v.object({
        kind: v.union(v.literal("maximum"), v.literal("minimum")),
        tempC: v.number(),
        tempF: v.number(),
        forecastTimeUtc: v.number(),
        forecastTimeLocal: v.string(),
        date: v.string(),
        rawGroup: v.string(),
      }),
    ),
    periods: v.array(
      v.object({
        timeFromUtc: v.number(),
        timeToUtc: v.number(),
        timeFromLocal: v.string(),
        timeToLocal: v.string(),
        changeType: v.optional(v.string()),
        probability: v.optional(v.number()),
        weather: v.optional(v.string()),
        cloudSummary: v.optional(v.string()),
        visibilitySm: v.optional(v.number()),
        windDirectionDeg: v.optional(v.number()),
        windSpeedKt: v.optional(v.number()),
      }),
    ),
    firstSeenAt: v.number(),
    lastSeenAt: v.number(),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_station_taf_key", ["stationIcao", "tafKey"])
    .index("by_station_issue_time", ["stationIcao", "issueTimeUtc"]),

  mexicoSmnForecastCaptures: defineTable({
    stationIcao: v.string(),
    source: v.literal("smn_municipal_hourly"),
    sourceUrl: v.string(),
    municipalityStateId: v.string(),
    municipalityId: v.string(),
    municipalityName: v.string(),
    stateName: v.string(),
    sourceLatitude: v.number(),
    sourceLongitude: v.number(),
    distanceFromAirportKm: v.number(),
    capturedAt: v.number(),
    capturedAtLocal: v.string(),
    captureDate: v.string(),
    sourceLastModifiedAt: v.optional(v.number()),
    rawHash: v.string(),
    compressedBytes: v.number(),
    decompressedBytes: v.number(),
    totalObjectCount: v.number(),
    targetRowCount: v.number(),
    rawMunicipalityRows: v.string(),
    createdAt: v.number(),
  }).index("by_station_captured_at", ["stationIcao", "capturedAt"]),

  mexicoSmnHourlyForecasts: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    forecastTimeUtc: v.number(),
    forecastTimeLocal: v.string(),
    tempC: v.number(),
    tempF: v.number(),
    conditionText: v.string(),
    conditionKey: v.string(),
    precipitationProbabilityPct: v.optional(v.number()),
    precipitationMm: v.optional(v.number()),
    humidityPct: v.optional(v.number()),
    dewpointC: v.optional(v.number()),
    dewpointF: v.optional(v.number()),
    windSpeedKph: v.optional(v.number()),
    windDirectionText: v.optional(v.string()),
    windDirectionDeg: v.optional(v.number()),
    windGustKph: v.optional(v.number()),
    utcOffsetHours: v.number(),
    sourceRowJson: v.string(),
    source: v.literal("smn_municipal_hourly"),
    sourceSiteLabel: v.string(),
    capturedAt: v.number(),
    sourceLastModifiedAt: v.optional(v.number()),
    forecastCaptureId: v.id("mexicoSmnForecastCaptures"),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_station_date_time", ["stationIcao", "date", "forecastTimeUtc"])
    .index("by_station_time", ["stationIcao", "forecastTimeUtc"]),

  mexicoPolymarketProbabilitySnapshots: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    snapshotKey: v.string(),
    eventId: v.string(),
    eventSlug: v.string(),
    eventTitle: v.string(),
    eventUrl: v.string(),
    eventActive: v.boolean(),
    eventClosed: v.boolean(),
    source: v.literal("polymarket_gamma"),
    sourceUpdatedAt: v.optional(v.number()),
    gammaUrl: v.string(),
    probabilitySource: v.literal("gamma_outcome_price"),
    probabilities: v.array(
      v.object({
        marketId: v.string(),
        marketSlug: v.string(),
        conditionId: v.string(),
        label: v.string(),
        displayOrder: v.number(),
        yesTokenId: v.string(),
        yesOutcomePrice: v.number(),
        yesProbabilityPct: v.number(),
        yesBestBidPct: v.optional(v.number()),
        yesBestAskPct: v.optional(v.number()),
        yesLastTradePricePct: v.optional(v.number()),
      }),
    ),
    collectionTrigger: v.union(v.literal("manual"), v.literal("scheduled")),
    fetchStartedAt: v.number(),
    fetchCompletedAt: v.number(),
    capturedAt: v.number(),
    capturedAtLocal: v.string(),
    responseBytes: v.number(),
    createdAt: v.number(),
  })
    .index("by_station_snapshot_key", ["stationIcao", "snapshotKey"])
    .index("by_station_date_captured", ["stationIcao", "date", "capturedAt"]),

  mexicoEdgeMarketEvents: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    seriesId: v.string(),
    seriesSlug: v.string(),
    source: v.string(),
    gammaUrl: v.string(),
    eventId: v.string(),
    eventSlug: v.string(),
    eventTitle: v.string(),
    eventUrl: v.string(),
    description: v.optional(v.string()),
    resolutionSource: v.optional(v.string()),
    endTimeUtc: v.optional(v.number()),
    endTimeIso: v.optional(v.string()),
    eventActive: v.boolean(),
    eventClosed: v.boolean(),
    negRisk: v.boolean(),
    sourceUpdatedAt: v.optional(v.number()),
    markets: v.array(mexicoEdgeMarketDefinition),
    marketCount: v.number(),
    fetchedAt: v.number(),
    receivedAt: v.number(),
    updatedAt: v.number(),
    createdAt: v.number(),
  }).index("by_station_date", ["stationIcao", "date"]),

  mexicoEdgeMarketQuotes: defineTable({
    ...mexicoEdgeQuoteFields,
  })
    .index("by_station_date", ["stationIcao", "date"])
    .index("by_station_date_market", ["stationIcao", "date", "marketId"]),

  mexicoEdgeMarketQuoteEvents: defineTable({
    ...mexicoEdgeQuoteFields,
    eventType: v.string(),
    changedFields: v.array(v.string()),
    trigger: v.string(),
    // Added after quote-event collection began, so these remain optional in
    // the schema for legacy rows. Approved evidence writes supply them; the
    // fail-closed legacy path deliberately omits them.
    pollGeneration: v.optional(v.string()),
    detectionStartAt: v.optional(v.number()),
    detectionEndAt: v.optional(v.number()),
    detectionIntervalKind: v.optional(
      v.union(v.literal("bounded"), v.literal("left_unbounded")),
    ),
  })
    .index("by_station_date_received", ["stationIcao", "date", "receivedAt"])
    .index("by_station_date_market_received", [
      "stationIcao",
      "date",
      "marketId",
      "receivedAt",
    ])
    .index("by_station_date_token_received", [
      "stationIcao",
      "date",
      "yesTokenId",
      "receivedAt",
    ])
    .index("by_station_received_at", ["stationIcao", "receivedAt"])
    .index("by_received_at", ["receivedAt"]),

  // One compact, immutable row for every accepted per-market CLOB poll. These
  // rows preserve unchanged polls without copying sizes, hashes, market text,
  // or the rest of the full quote/event payload.
  mexicoEdgeMarketQuoteHeartbeats: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    source: v.string(),
    eventId: v.string(),
    marketId: v.string(),
    yesTokenId: v.string(),
    pollGeneration: v.string(),
    trigger: v.union(v.literal("manual"), v.literal("scheduled")),
    quoteFingerprint: v.string(),
    previousQuoteFingerprint: v.optional(v.string()),
    quoteChanged: v.boolean(),
    changedFields: v.array(v.string()),
    bestBidPrice: v.optional(v.string()),
    bestAskPrice: v.optional(v.string()),
    midpointPrice: v.optional(v.string()),
    spreadPrice: v.optional(v.string()),
    lastTradePrice: v.optional(v.string()),
    lastTradeSide: v.optional(v.string()),
    lastTradeStatus: v.optional(
      v.union(v.literal("reported"), v.literal("no_trades")),
    ),
    platformDisplayPrice: v.optional(v.string()),
    platformDisplaySource: v.string(),
    gammaReceivedAt: v.optional(v.number()),
    bookFetchStartedAt: v.optional(v.number()),
    bookReceivedAt: v.optional(v.number()),
    lastTradeFetchStartedAt: v.optional(v.number()),
    lastTradeReceivedAt: v.optional(v.number()),
    previousGammaReceivedAt: v.optional(v.number()),
    previousBookReceivedAt: v.optional(v.number()),
    previousLastTradeReceivedAt: v.optional(v.number()),
    fetchedAt: v.number(),
    receivedAt: v.number(),
    previousPollReceivedAt: v.optional(v.number()),
    createdAt: v.number(),
  })
    .index("by_station_date_market_received", [
      "stationIcao",
      "date",
      "marketId",
      "receivedAt",
    ])
    .index("by_station_date_generation_market", [
      "stationIcao",
      "date",
      "pollGeneration",
      "marketId",
    ])
    .index("by_station_received_at", ["stationIcao", "receivedAt"])
    .index("by_received_at", ["receivedAt"]),

  mexicoEdgeMarketStreamStatus: defineTable({
    stationIcao: v.string(),
    transport: v.string(),
    websocketStatus: v.string(),
    websocketReason: v.string(),
    totalPollCount: v.number(),
    totalChangedQuoteCount: v.number(),
    collectionEnabled: v.boolean(),
    status: v.string(),
    activeDate: v.string(),
    generation: v.string(),
    leaseUntil: v.number(),
    lastError: v.string(),
    trigger: v.optional(v.string()),
    lastAttemptAt: v.optional(v.number()),
    lastCompletedAt: v.optional(v.number()),
    lastSuccessAt: v.optional(v.number()),
    responseBytes: v.optional(v.number()),
    marketCount: v.optional(v.number()),
    lastChangedQuoteCount: v.optional(v.number()),
    updatedAt: v.number(),
  }).index("by_station", ["stationIcao"]),

  // Immutable source-specific daily-high revisions for the edge cockpit.
  // TAF TX airport guidance and SMN municipal guidance intentionally remain
  // separate series; sourceInputKey makes repeated derivation idempotent.
  mexicoEdgeForecastHighSnapshots: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    source: v.union(v.literal("taf_tx"), v.literal("smn_municipal_hourly")),
    snapshotKey: v.string(),
    sourceInputKey: v.string(),
    sourceLabel: v.string(),
    sourceIssuedAt: v.optional(v.number()),
    sourceCapturedAt: v.number(),
    forecastHighC: v.number(),
    forecastHighF: v.number(),
    forecastPeakTimeUtc: v.optional(v.number()),
    forecastPeakTimeLocal: v.optional(v.string()),
    createdAt: v.number(),
  })
    .index("by_station_snapshot_key", ["stationIcao", "snapshotKey"])
    .index("by_station_date_source_capture", [
      "stationIcao",
      "date",
      "source",
      "sourceCapturedAt",
    ])
    .index("by_station_source_input", [
      "stationIcao",
      "source",
      "sourceInputKey",
    ]),

  mexicoCapmaTdzObservations: defineTable({
    stationIcao: v.string(),
    tdz: v.union(v.literal("05"), v.literal("23")),
    date: v.string(),
    screenTimeUtc: v.number(),
    screenTimeLocal: v.string(),
    screenTimestampRaw: v.string(),
    currentTempC: v.number(),
    currentTempF: v.number(),
    twoMinuteTempC: v.number(),
    twoMinuteTempF: v.number(),
    temperaturePrecisionC: v.number(),
    // Extended display fields (added 2026-08-22). Optional: each is stored
    // only when its independent OCR read and cross-checks validated. The dew
    // point is computed by the display from unrounded T/RH, so together with
    // integer % humidity these quantized channels support sub-degree
    // temperature inference over time.
    dewpointC: v.optional(v.number()),
    dewpointConfidence: v.optional(v.number()),
    humidityPercent: v.optional(v.number()),
    humidityConfidence: v.optional(v.number()),
    stationPressureHpa: v.optional(v.number()),
    stationPressureConfidence: v.optional(v.number()),
    qnhInHg: v.optional(v.number()),
    qnhConfidence: v.optional(v.number()),
    twoMinuteDewpointC: v.optional(v.number()),
    twoMinuteDewpointConfidence: v.optional(v.number()),
    // Which network path served the frame: "direct" Convex egress, or
    // "vercel_relay" through the allowlisted alternate-egress relay used
    // when direct TCP connects to the owner host are dropped.
    fetchTransport: v.optional(
      v.union(v.literal("direct"), v.literal("vercel_relay")),
    ),
    sourceUrl: v.string(),
    sourceSiteLabel: v.string(),
    rawHash: v.string(),
    etag: v.optional(v.string()),
    relayLastModifiedAt: v.optional(v.number()),
    firstSeenAt: v.number(),
    fetchStartedAt: v.number(),
    fetchCompletedAt: v.number(),
    responseBytes: v.number(),
    imageWidth: v.number(),
    imageHeight: v.number(),
    ocrConfidence: v.number(),
    ocrEngine: v.string(),
    trigger: v.union(v.literal("manual"), v.literal("scheduled")),
    lastSeenAt: v.number(),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_station_tdz_hash", ["stationIcao", "tdz", "rawHash"])
    .index("by_station_screen_time", ["stationIcao", "screenTimeUtc"])
    .index("by_station_date_screen_time", [
      "stationIcao",
      "date",
      "screenTimeUtc",
    ]),

  // Historical OCR rows remain in mexicoCapmaTdzObservations, but raw image
  // retention is intentionally bounded to one replaceable object per TDZ.
  mexicoCapmaLatestImages: defineTable({
    stationIcao: v.string(),
    tdz: v.union(v.literal("05"), v.literal("23")),
    storageId: v.id("_storage"),
    rawHash: v.string(),
    storageSha256: v.string(),
    contentType: v.literal("image/jpeg"),
    sourceUrl: v.string(),
    sourceSiteLabel: v.string(),
    screenTimeUtc: v.number(),
    screenTimeLocal: v.string(),
    screenTimestampRaw: v.string(),
    currentTempC: v.number(),
    twoMinuteTempC: v.number(),
    fetchStartedAt: v.number(),
    fetchCompletedAt: v.number(),
    responseBytes: v.number(),
    imageWidth: v.number(),
    imageHeight: v.number(),
    ocrConfidence: v.number(),
    etag: v.optional(v.string()),
    relayLastModifiedAt: v.optional(v.number()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_station_tdz", ["stationIcao", "tdz"])
    .index("by_storage_id", ["storageId"]),
});
