//convex/schema.js
import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  notes: defineTable({
    title: v.optional(v.string()),
    body: v.optional(v.string()),
    imageIds: v.array(v.id("_storage")),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_createdAt", ["createdAt"]),

  monthRuns: defineTable({
    stationIcao: v.string(),
    stationIem: v.string(),
    year: v.number(),
    month: v.number(),
    manualUnit: v.union(v.literal("C"), v.literal("F")),
    createdAt: v.number(),
    updatedAt: v.number(),
    metarLastComputedAt: v.optional(v.number()),
    metarLastStatus: v.union(
      v.literal("idle"),
      v.literal("computing"),
      v.literal("ok"),
      v.literal("error"),
    ),
    metarLastError: v.optional(v.string()),
    metarAllLastComputedAt: v.optional(v.number()),
    metarAllLastStatus: v.optional(
      v.union(
        v.literal("idle"),
        v.literal("computing"),
        v.literal("ok"),
        v.literal("error"),
      ),
    ),
    metarAllLastError: v.optional(v.string()),
  }).index("by_station_month", ["stationIcao", "year", "month"]),

  dailyComparisons: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    manualMaxC: v.optional(v.number()),
    manualMaxF: v.optional(v.number()),
    manualNotes: v.optional(v.string()),
    metarMaxC: v.optional(v.number()),
    metarMaxF: v.optional(v.number()),
    metarMaxAtUtc: v.optional(v.number()),
    metarMaxAtLocal: v.optional(v.string()),
    metarObsCount: v.optional(v.number()),
    metarMaxRaw: v.optional(v.string()),
    metarMaxSource: v.optional(v.string()),
    deltaC: v.optional(v.number()),
    deltaF: v.optional(v.number()),
    metarAllMaxC: v.optional(v.number()),
    metarAllMaxF: v.optional(v.number()),
    metarAllMaxAtUtc: v.optional(v.number()),
    metarAllMaxAtLocal: v.optional(v.string()),
    metarAllObsCount: v.optional(v.number()),
    metarAllMaxRaw: v.optional(v.string()),
    metarAllMaxSource: v.optional(v.string()),
    deltaAllC: v.optional(v.number()),
    deltaAllF: v.optional(v.number()),
    updatedAt: v.number(),
  }).index("by_station_date", ["stationIcao", "date"]),

  kordPhoneCalls: defineTable({
    stationIcao: v.string(),
    date: v.string(), // YYYY-MM-DD (Chicago)
    slotLocal: v.string(), // YYYY-MM-DD HH:MM (Chicago) scheduled slot or manual trigger time
    tsUtc: v.optional(v.number()), // recording start (ms epoch)
    tsLocal: v.optional(v.string()), // YYYY-MM-DD HH:MM (Chicago), derived from tsUtc
    callSid: v.optional(v.string()),
    recordingSid: v.optional(v.string()),
    recordingUrl: v.optional(v.string()),
    recordingDuration: v.optional(v.number()),
    transcript: v.optional(v.string()),
    tempC: v.optional(v.number()),
    tempF: v.optional(v.number()),
    status: v.union(
      v.literal("queued"),
      v.literal("calling"),
      v.literal("recorded"),
      v.literal("transcribed"),
      v.literal("parsed"),
      v.literal("error"),
    ),
    error: v.optional(v.string()),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_station_date", ["stationIcao", "date"])
    .index("by_station_slot", ["stationIcao", "slotLocal"])
    .index("by_callSid", ["callSid"]),

  kordForecastSnapshots: defineTable({
    stationIcao: v.string(),
    stationName: v.string(),
    capturedAt: v.number(),
    capturedAtLocal: v.string(),
    durationDays: v.number(),
    unit: v.union(v.literal("imperial"), v.literal("metric")),
    language: v.string(),
    status: v.union(
      v.literal("ok"),
      v.literal("partial"),
      v.literal("error"),
    ),
    microsoftStatus: v.union(v.literal("ok"), v.literal("error")),
    microsoftError: v.optional(v.string()),
    microsoftForecastDays: v.array(
      v.object({
        date: v.string(),
        minTempC: v.optional(v.number()),
        minTempF: v.optional(v.number()),
        maxTempC: v.optional(v.number()),
        maxTempF: v.optional(v.number()),
        dayPhrase: v.optional(v.string()),
        nightPhrase: v.optional(v.string()),
      }),
    ),
    accuweatherStatus: v.optional(v.union(v.literal("ok"), v.literal("error"))),
    accuweatherError: v.optional(v.string()),
    accuweatherLocationKey: v.optional(v.string()),
    accuweatherForecastDays: v.optional(
      v.array(
        v.object({
          date: v.string(),
          minTempC: v.optional(v.number()),
          minTempF: v.optional(v.number()),
          maxTempC: v.optional(v.number()),
          maxTempF: v.optional(v.number()),
          dayPhrase: v.optional(v.string()),
          nightPhrase: v.optional(v.string()),
        }),
      ),
    ),
    googleStatus: v.optional(v.union(v.literal("ok"), v.literal("error"))),
    googleError: v.optional(v.string()),
    googleForecastDays: v.optional(
      v.array(
        v.object({
          date: v.string(),
          minTempC: v.optional(v.number()),
          minTempF: v.optional(v.number()),
          maxTempC: v.optional(v.number()),
          maxTempF: v.optional(v.number()),
          dayPhrase: v.optional(v.string()),
          nightPhrase: v.optional(v.string()),
        }),
      ),
    ),
    weathercomStatus: v.optional(v.union(v.literal("ok"), v.literal("error"))),
    weathercomError: v.optional(v.string()),
    weathercomForecastDays: v.optional(
      v.array(
        v.object({
          date: v.string(),
          minTempC: v.optional(v.number()),
          minTempF: v.optional(v.number()),
          maxTempC: v.optional(v.number()),
          maxTempF: v.optional(v.number()),
          dayPhrase: v.optional(v.string()),
          nightPhrase: v.optional(v.string()),
        }),
      ),
    ),
    actualReadings: v.array(
      v.object({
        source: v.string(),
        status: v.union(v.literal("ok"), v.literal("error")),
        observedAtUtc: v.optional(v.number()),
        observedAtLocal: v.optional(v.string()),
        tempC: v.optional(v.number()),
        tempF: v.optional(v.number()),
        raw: v.optional(v.string()),
        error: v.optional(v.string()),
      }),
    ),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_station_capturedAt", ["stationIcao", "capturedAt"]),

  kordCurrentSnapshots: defineTable({
    stationIcao: v.string(),
    stationName: v.string(),
    capturedAt: v.number(),
    capturedAtLocal: v.string(),
    unit: v.union(v.literal("imperial"), v.literal("metric")),
    language: v.string(),
    status: v.union(
      v.literal("ok"),
      v.literal("partial"),
      v.literal("error"),
    ),
    actualReadings: v.array(
      v.object({
        source: v.string(),
        status: v.union(v.literal("ok"), v.literal("error")),
        observedAtUtc: v.optional(v.number()),
        observedAtLocal: v.optional(v.string()),
        tempC: v.optional(v.number()),
        tempF: v.optional(v.number()),
        raw: v.optional(v.string()),
        error: v.optional(v.string()),
      }),
    ),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_station_capturedAt", ["stationIcao", "capturedAt"]),

  kordForecastPredictions: defineTable({
    stationIcao: v.string(),
    provider: v.union(
      v.literal("microsoft"),
      v.literal("accuweather"),
      v.literal("google"),
      v.literal("weathercom"),
    ),
    targetDate: v.string(),
    capturedAt: v.number(),
    capturedAtLocal: v.string(),
    captureDate: v.string(),
    leadDays: v.number(),
    minTempC: v.optional(v.number()),
    minTempF: v.optional(v.number()),
    maxTempC: v.optional(v.number()),
    maxTempF: v.optional(v.number()),
    dayPhrase: v.optional(v.string()),
    nightPhrase: v.optional(v.string()),
    snapshotId: v.id("kordForecastSnapshots"),
    createdAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_station_provider_target_capturedAt", [
      "stationIcao",
      "provider",
      "targetDate",
      "capturedAt",
    ])
    .index("by_snapshotId", ["snapshotId"]),

  metarObservations: defineTable({
    stationIcao: v.string(),
    mode: v.union(v.literal("official"), v.literal("all")),
    date: v.string(),
    tsUtc: v.number(),
    tsLocal: v.string(),
    tempC: v.number(),
    tempF: v.number(),
    rawMetar: v.string(),
    source: v.string(),
    noaaFirstSeenAt: v.optional(v.number()),
    updatedAt: v.number(),
  }).index("by_station_mode_date_ts", ["stationIcao", "mode", "date", "tsUtc"]),

  synopticObservations: defineTable({
    stationIcao: v.string(),
    provider: v.string(),
    source: v.string(),
    date: v.string(),
    obsTimeUtc: v.number(),
    obsTimeLocal: v.string(),
    tempC: v.optional(v.number()),
    tempF: v.optional(v.number()),
    dewpointC: v.optional(v.number()),
    dewpointF: v.optional(v.number()),
    relativeHumidity: v.optional(v.number()),
    windDirDegrees: v.optional(v.number()),
    windSpeedMph: v.optional(v.number()),
    windSpeedMps: v.optional(v.number()),
    visibilityMiles: v.optional(v.number()),
    ceilingFt: v.optional(v.number()),
    altimeterInHg: v.optional(v.number()),
    seaLevelPressureMb: v.optional(v.number()),
    weatherCondition: v.optional(v.string()),
    weatherSummary: v.optional(v.string()),
    metarOrigin: v.optional(v.string()),
    rawMetar: v.optional(v.string()),
    firstSeenAt: v.number(),
    lastSeenAt: v.number(),
    updatedAt: v.number(),
  }).index("by_station_date_ts", ["stationIcao", "date", "obsTimeUtc"]),

  synopticDailySummaries: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    obsCount: v.number(),
    latestObsTimeUtc: v.optional(v.number()),
    latestObsTimeLocal: v.optional(v.string()),
    latestRawMetar: v.optional(v.string()),
    latestMetarOrigin: v.optional(v.string()),
    maxTempC: v.optional(v.number()),
    maxTempF: v.optional(v.number()),
    maxTempAtUtc: v.optional(v.number()),
    maxTempAtLocal: v.optional(v.string()),
    minTempC: v.optional(v.number()),
    minTempF: v.optional(v.number()),
    minTempAtUtc: v.optional(v.number()),
    minTempAtLocal: v.optional(v.string()),
    updatedAt: v.number(),
  }).index("by_station_date", ["stationIcao", "date"]),

  madisHfmObservations: defineTable({
    stationIcao: v.string(),
    provider: v.string(),
    source: v.string(),
    date: v.string(),
    obsTimeUtc: v.number(),
    obsTimeLocal: v.string(),
    tempC: v.optional(v.number()),
    tempF: v.optional(v.number()),
    dewpointC: v.optional(v.number()),
    dewpointF: v.optional(v.number()),
    relativeHumidity: v.optional(v.number()),
    windDirDegrees: v.optional(v.number()),
    windSpeedMps: v.optional(v.number()),
    windGustMps: v.optional(v.number()),
    altimeterPa: v.optional(v.number()),
    dewpointQcd: v.optional(v.string()),
    relativeHumidityQcd: v.optional(v.string()),
    tempQcd: v.optional(v.string()),
    windDirQcd: v.optional(v.string()),
    windSpeedQcd: v.optional(v.string()),
    windGustQcd: v.optional(v.string()),
    altimeterQcd: v.optional(v.string()),
    firstSeenAt: v.number(),
    lastSeenAt: v.number(),
    updatedAt: v.number(),
  }).index("by_station_date_ts", ["stationIcao", "date", "obsTimeUtc"]),

  madisHfmDailySummaries: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    obsCount: v.number(),
    latestObsTimeUtc: v.optional(v.number()),
    latestObsTimeLocal: v.optional(v.string()),
    maxTempC: v.optional(v.number()),
    maxTempF: v.optional(v.number()),
    maxTempAtUtc: v.optional(v.number()),
    maxTempAtLocal: v.optional(v.string()),
    minTempC: v.optional(v.number()),
    minTempF: v.optional(v.number()),
    minTempAtUtc: v.optional(v.number()),
    minTempAtLocal: v.optional(v.string()),
    updatedAt: v.number(),
  }).index("by_station_date", ["stationIcao", "date"]),

  weatherComPwsObservations: defineTable({
    stationIcao: v.string(),
    pwsStationId: v.string(),
    source: v.string(),
    keySource: v.string(),
    date: v.string(),
    obsTimeUtc: v.number(),
    obsTimeLocal: v.string(),
    neighborhood: v.optional(v.string()),
    softwareType: v.optional(v.string()),
    country: v.optional(v.string()),
    latitude: v.optional(v.number()),
    longitude: v.optional(v.number()),
    qcStatus: v.optional(v.number()),
    realtimeFrequency: v.optional(v.number()),
    solarRadiation: v.optional(v.number()),
    uv: v.optional(v.number()),
    relativeHumidity: v.optional(v.number()),
    windDirDegrees: v.optional(v.number()),
    tempC: v.optional(v.number()),
    tempF: v.optional(v.number()),
    dewpointC: v.optional(v.number()),
    dewpointF: v.optional(v.number()),
    heatIndexC: v.optional(v.number()),
    heatIndexF: v.optional(v.number()),
    windChillC: v.optional(v.number()),
    windChillF: v.optional(v.number()),
    windSpeedMph: v.optional(v.number()),
    windSpeedMps: v.optional(v.number()),
    windGustMph: v.optional(v.number()),
    windGustMps: v.optional(v.number()),
    pressureInHg: v.optional(v.number()),
    pressureHpa: v.optional(v.number()),
    precipRateIn: v.optional(v.number()),
    precipTotalIn: v.optional(v.number()),
    elevFt: v.optional(v.number()),
    firstSeenAt: v.number(),
    lastSeenAt: v.number(),
    updatedAt: v.number(),
  })
    .index("by_station_pws_date_ts", [
      "stationIcao",
      "pwsStationId",
      "date",
      "obsTimeUtc",
    ])
    .index("by_station_date_ts", ["stationIcao", "date", "obsTimeUtc"]),

  weatherComPwsDailySummaries: defineTable({
    stationIcao: v.string(),
    pwsStationId: v.string(),
    source: v.string(),
    keySource: v.string(),
    date: v.string(),
    obsCount: v.number(),
    latestObsTimeUtc: v.optional(v.number()),
    latestObsTimeLocal: v.optional(v.string()),
    latestTempC: v.optional(v.number()),
    latestTempF: v.optional(v.number()),
    latestQcStatus: v.optional(v.number()),
    latestNeighborhood: v.optional(v.string()),
    maxTempC: v.optional(v.number()),
    maxTempF: v.optional(v.number()),
    maxTempAtUtc: v.optional(v.number()),
    maxTempAtLocal: v.optional(v.string()),
    minTempC: v.optional(v.number()),
    minTempF: v.optional(v.number()),
    minTempAtUtc: v.optional(v.number()),
    minTempAtLocal: v.optional(v.string()),
    updatedAt: v.number(),
  })
    .index("by_station_pws_date", ["stationIcao", "pwsStationId", "date"])
    .index("by_station_date", ["stationIcao", "date"]),

  redemetMetarObservations: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    obsTimeUtc: v.number(),
    obsTimeLocal: v.string(),
    reportType: v.union(v.literal("METAR"), v.literal("SPECI")),
    tempC: v.number(),
    tempF: v.number(),
    rawMetar: v.string(),
    source: v.string(),
    redemetFirstSeenAt: v.optional(v.number()),
    updatedAt: v.number(),
  }).index("by_station_date_ts", ["stationIcao", "date", "obsTimeUtc"]),

  redemetDailySummaries: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    obsCount: v.number(),
    latestObsTimeUtc: v.optional(v.number()),
    latestObsTimeLocal: v.optional(v.string()),
    latestReportType: v.optional(v.string()),
    latestTempC: v.optional(v.number()),
    latestTempF: v.optional(v.number()),
    latestRawMetar: v.optional(v.string()),
    maxTempC: v.optional(v.number()),
    maxTempF: v.optional(v.number()),
    maxTempAtUtc: v.optional(v.number()),
    maxTempAtLocal: v.optional(v.string()),
    minTempC: v.optional(v.number()),
    minTempF: v.optional(v.number()),
    minTempAtUtc: v.optional(v.number()),
    minTempAtLocal: v.optional(v.string()),
    updatedAt: v.number(),
  }).index("by_station_date", ["stationIcao", "date"]),

  redemetPublishRaceReports: defineTable({
    stationIcao: v.string(),
    reportDateLocal: v.string(),
    reportTsUtc: v.number(),
    reportType: v.optional(v.union(v.literal("METAR"), v.literal("SPECI"))),
    rawMetar: v.optional(v.string()),
    redemetRawMetar: v.optional(v.string()),
    tgftpRawMetar: v.optional(v.string()),
    redemetFirstSeenAt: v.optional(v.number()),
    tgftpFirstSeenAt: v.optional(v.number()),
    tgftpLastModifiedAt: v.optional(v.number()),
    winner: v.optional(
      v.union(v.literal("redemet"), v.literal("tgftp"), v.literal("tie")),
    ),
    leadMs: v.optional(v.number()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_station_reportTs", ["stationIcao", "reportTsUtc"]),

  preflightMetarObservations: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    obsTimeUtc: v.number(),
    obsTimeLocal: v.string(),
    reportType: v.union(v.literal("METAR"), v.literal("SPECI")),
    tempC: v.number(),
    tempF: v.number(),
    rawMetar: v.string(),
    source: v.string(),
    preflightFirstSeenAt: v.optional(v.number()),
    updatedAt: v.number(),
  }).index("by_station_date_ts", ["stationIcao", "date", "obsTimeUtc"]),

  preflightDailySummaries: defineTable({
    stationIcao: v.string(),
    date: v.string(),
    obsCount: v.number(),
    latestObsTimeUtc: v.optional(v.number()),
    latestObsTimeLocal: v.optional(v.string()),
    latestReportType: v.optional(v.string()),
    latestTempC: v.optional(v.number()),
    latestTempF: v.optional(v.number()),
    latestRawMetar: v.optional(v.string()),
    maxTempC: v.optional(v.number()),
    maxTempF: v.optional(v.number()),
    maxTempAtUtc: v.optional(v.number()),
    maxTempAtLocal: v.optional(v.string()),
    minTempC: v.optional(v.number()),
    minTempF: v.optional(v.number()),
    minTempAtUtc: v.optional(v.number()),
    minTempAtLocal: v.optional(v.string()),
    updatedAt: v.number(),
  }).index("by_station_date", ["stationIcao", "date"]),

  preflightPublishRaceReports: defineTable({
    stationIcao: v.string(),
    reportDateLocal: v.string(),
    reportTsUtc: v.number(),
    reportType: v.optional(v.union(v.literal("METAR"), v.literal("SPECI"))),
    rawMetar: v.optional(v.string()),
    preflightRawMetar: v.optional(v.string()),
    tgftpRawMetar: v.optional(v.string()),
    preflightFirstSeenAt: v.optional(v.number()),
    tgftpFirstSeenAt: v.optional(v.number()),
    tgftpLastModifiedAt: v.optional(v.number()),
    winner: v.optional(
      v.union(v.literal("preflight"), v.literal("tgftp"), v.literal("tie")),
    ),
    leadMs: v.optional(v.number()),
    createdAt: v.number(),
    updatedAt: v.number(),
  }).index("by_station_reportTs", ["stationIcao", "reportTsUtc"]),
});
